### ISSUE TITLE
Add lint rule to prohibit object-shorthand

### ISSUE THREAD

**Issue by zepumph** [phetsims/chipper#739] opened 2019-02-06 22:14 UTC
Related to https://github.com/phetsims/gravity-force-lab/issues/148. @samreid today told me that using object-shorthand didn't pass a recent code review of his (couldn't find an issue for that):
```
( x, y, z ) => {
  return { x, y, z };
}
```

If this is indeed true, then we should add a lint rule to make sure that this isn't allowed. 

When @samreid, @chrisklus, and @zepumph added this lint rule like:

`    'object-shorthand': [ 'error', 'never' ],`

we found 345 errors. We should handle this before we have 3400 to deal with. Marking for dev meeting.

**Comment by samreid** [comment] 2019-02-06 22:16
> @samreid today told me that using object-shorthand didn't pass a recent code review of his (couldn't find an issue for that):

To clarify, I recalled a developer meeting where @jbphet pointed out that using the object key shorthand means that if you refactor a variable name, it also renames the object key which is generally undesirable.  There was agreement from the group that this is problematic, and we decided that PhET generally shouldn't use this object shorthand.  @chrisklus also recalled this conversation.

**Comment by pixelzoom** [comment] 2019-02-07 03:26
I also recall that dev conversation.

**Comment by pixelzoom** [comment] 2019-02-07 03:29
If anyone cares to bone up on the `object-shorthand` rule, see https://eslint.org/docs/2.0.0/rules/object-shorthand.

**Comment by samreid** [comment] 2019-02-07 03:39
I was surprised and excited to see that eslint can automatically fill in the object keys.  This patch combined with the rule can accomplish it.

```
Index: js/grunt/lint.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- js/grunt/lint.js	(revision aecd7b281ce4e9fc13622d394d09cdf625d16496)
+++ js/grunt/lint.js	(date 1549510707000)
@@ -35,6 +35,8 @@
     // grunt was run from.
     cache: cache,
 
+    fix: true,
+
     // Our custom rules live here
     rulePaths: [ 'chipper/eslint/rules' ],
 
@@ -78,5 +80,8 @@
   report.warningCount && grunt.fail.warn( report.warningCount + ' Lint Warnings' );
   report.errorCount && grunt.fail.fatal( report.errorCount + ' Lint Errors' );
 
+  // output fixes to disk
+  eslint.CLIEngine.outputFixes( report );
+
   return report;
 };
```

**Comment by samreid** [comment] 2019-02-07 03:40
Well, it is also adding `: function` some places where that doesn't seem necessary.

**Comment by samreid** [comment] 2019-02-14 19:48
We decided we would like to forbid this rule because the object shorthand makes refactoring difficult.

**Comment by samreid** [comment] 2019-02-15 21:03
Unfortunately, this rule flags:

```js
_.extend( {
            listener() {
              model.levelProperty.value = null;
            }
          }, leftButtonOptions )
```

and rewrites it as:

```js
_.extend( {
            listener: function() {
              model.levelProperty.value = null;
            }
          }, leftButtonOptions )
```

**Comment by samreid** [comment] 2019-02-15 21:27
I reverted the shorthand for non-functions.  For the functions, it looks like these are being used inconsistently:

![image](https://user-images.githubusercontent.com/679486/52885131-6d62ed80-312d-11e9-951e-1f779d7b89fd.png)

And other places seem like they could be using arrow functions instead:

![image](https://user-images.githubusercontent.com/679486/52885180-94b9ba80-312d-11e9-9ed7-82da379b2d70.png)

However, I will wait until we have a consensus (or at least some 👍 ) on the object literal function shorthand before committing these (43 files across 19 repos).

**Comment by zepumph** [comment] 2019-02-21 01:27
I personally use "object shorthand" for functions quite often. If we decide not to, then I can convert to arrow functions, but sometimes I prefer them because they look a bit cleaner. No strong preference here. Furthermore I don't necessarily feel strongly about making a convention that all devs must follow. Developer discretion seems totally fine to me (on arrow func vs object shorthand).

**Comment by pixelzoom** [comment] 2019-02-21 18:55
2/21/19 dev meeting:
* We'd like to have object shorthand for functions. 
* Is it possible to write a rule that can differentiate between shorthand for objects vs functions? @zepumph will investigate.
* If there's not a rule, rely on code review and/or manually enabling rule.

When to use each form:
* For class methods, prefer `methodName() {...}`.
* In options `inherit`, use `methodName() {...}` or `methodName: function(...) {...}`.
* In other cases, up to developer discretion.

**Comment by samreid** [comment] 2019-02-21 18:55
Also a note to add this rule to the "code review" eslint rules.

**Comment by zepumph** [comment] 2019-02-21 20:19
Indeed I could not get the built-in eslint object-shorthand rule to work for us. What we really wanted, as @samreid mentioned in dev meeting, was something like "never properties", which doesn't exist.

So I went and copied the source code for the rule (see link below), and adapted it to fail only on properties, not methods. This is now checked in under `phet-object-shorthand` and doesn't support options, but instead will just error on object-shorthand for properties. I tested this and things seemed to work well. It also flagged the object shorthand in WilderModel.js, so I disabled that rule there, with a 
 note that we don't support this rule. 

https://github.com/eslint/eslint/blob/550de1e611a1e9af873bcb18d74cf2056e8d2e1b/lib/rules/object-shorthand.js

@samreid will you please review.

**Comment by samreid** [comment] 2019-02-23 04:21
This is a great solution, I'm glad you thought of it!  I tested and confirmed that the newly introduced rule allowed function shorthand but disallowed property shorthand.

I think this rule should be moved from chipper/eslint/sim_es6_eslintrc.js to chipper/eslint/.eslintrc.js.  That will help us catch where it is accidentally introduced in simulations or other code that is not explicitly marked as ES6.  For instance, when I tried moving it there, it caught this:

chipper/eslint/rules/phet-object-shorthand.js
  43:11  error  Expected longform property syntax  phet-object-shorthand

```js
        // { x } should be written as { x: x }
        context.report( {
          node,
          message: 'Expected longform property syntax.',
          fix: fixer => fixer.insertTextAfter( node.key, `: ${node.key.name}` )
        } );
```

One additional thought that may serve us better in the long run:  We could:
1.  create an issue on the ESLint repo describing why we want to avoid property shorthand but allow method shorthand.  Maybe other teams will have this same desire.  Or maybe we will have a valuable discussion about this.
2. propose an API that supports our needs and doesn't disrupt the existing API for that rule
3. submit a pull request to eslint that implements the desired behavior (along with unit test and examples)

That way we move responsibility for this feature to the eslint community.  It may help preserve that functionality in the long run, across eslint major version updates.

**Comment by zepumph** [comment] 2019-03-01 02:42
Assigning to high priority (but for my misc time) so it doesn't fall off my radar.

**Comment by zepumph** [comment] 2019-03-08 01:39
>43:11 error Expected longform property syntax phet-object-shorthand

awkward. . . . Fix committed above. I moved the lint rule as well. That sounds like a good plan.

As for your suggestion, I agree about the issue in eslint repo. I think it will be helpful. Though I'm not sure when I'll have time.

**Comment by zepumph** [comment] 2019-11-07 23:59
@samreid, your comment in https://github.com/phetsims/chipper/issues/739#issuecomment-466615163 inspired me to make an issue for https://github.com/phetsims/chipper/issues/794. Originally I tried getting back to this one, but the rule is quite a bit more complicated. I wish I had created an eslint issue right now, but at this point, it would likely take me more time to understand it again than the benefit we would get out of having eslint support this. I say this also recognizing that the currently committed phet lint rule is only 45 lines of code, and seems relatively maintainable. 

How does that sound to you? Please close or recommend another option.

**Comment by samreid** [comment] 2019-11-08 17:01
I'm glad we have our own rule for this and I don't think we need to take the time now to bring this to the attention of the ESLint community.  In the future, if there is a major breaking change version of ESLint and it becomes difficult to port our specific lint rule, we could re-evaluate, but for now it seems good to close.  Thanks!

**Closed by samreid** 2019-11-08 17:01 UTC
Labels: type:misc
