### ISSUE TITLE
Why is the build directory getting sub-deployed?

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#539] opened 2017-01-06 19:53 UTC
I noticed http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-black-box-study/1.0.6-phetio/

had a nested "build" directory. Why?

![image](https://cloud.githubusercontent.com/assets/679486/21730902/221ded2a-d40f-11e6-902b-370d6216f84e.png)

**Comment by samreid** [comment] 2017-01-23 22:27
@mattpen did you see something like this recently, perhaps in perennial?

**Comment by mattpen** [comment] 2017-01-25 17:07
https://github.com/phetsims/perennial/commit/1867a7f688698f74cfce9e2363ecaefe4c1c1c2d

This commit is probably the reason.  I guess I don't understand which files exactly should be copied to spot.  Can we create a list of files that should and should not be copied?

**Comment by mattpen** [comment] 2017-01-26 18:16
We investigated this in dev meeting.  The leading hypothesis is that this is caused by a bug in an old sha of chipper, and has not happened since.  We'll check again in a month.

**Comment by mattpen** [comment] 2017-03-09 07:38
Adding to developer meeting to discuss if anyone has seen strange artifacts like this in the build directory in the past month.

**Comment by mattpen** [comment] 2017-03-09 07:41
We should also discuss closing https://github.com/phetsims/chipper/issues/539 if builds have been going as expected.

**Comment by samreid** [comment] 2017-03-09 16:48
I haven't seen any problems recently.

**Comment by mattpen** [comment] 2017-03-09 17:50
No one reported any nested build directories in the last month at dev meeting.  Closing.

**Closed by mattpen** 2017-03-09 17:50 UTC
Labels: dev:phet-io, priority:5-deferred
