### ISSUE TITLE
some grunt tasks shouldn't be tasks

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#133] opened 2015-04-23 19:15 UTC
generateLicenseText should be a utility function that's called where needed. It's not something that would be invoked as a task, and all it currently does is set a global (global.phet.licenseText).

**Comment by pixelzoom** [comment] 2015-04-27 21:21
before-requirejs-build and after-requirejs-build probably shouldn't be registered as grunt tasks either, since they are not intended to be run standalone.

**Comment by jonathanolson** [comment] 2015-04-28 01:01
The problem is that the require.js step of the build isn't meant to be standalone, but it is its own grunt task.

We need things done before and after that task is run, although I totally agree that having them as tasks seems wrong with how we have been handling tasks.

We could think of certain tasks as 'steps' in a parent task instead?

**Comment by pixelzoom** [comment] 2015-04-28 14:46
So should I put on this issue, and write getPreloads (https://github.com/phetsims/chipper/issues/130) as a grunt task that provides a "return value" by setting a global?

**Comment by samreid** [comment] 2015-04-28 17:03
Can it be done as a function instead of a grunt task?  That seems more maintainable.

**Comment by pixelzoom** [comment] 2015-04-28 18:06
set-preload is now also a grunt task, see #130.  So add it to the list of things that are questionable as tasks.

I'm going to unassign and defer this issue.

**Comment by pixelzoom** [comment] 2015-05-08 19:34
Note: generateLicenseText is now setLicenseText.

**Comment by pixelzoom** [comment] 2015-08-10 22:10
@samreid I think you recently converted several tasks to functions. Is there anything more to do here?

**Comment by samreid** [comment] 2015-08-11 03:36
Here are the remaining tasks I am wondering if we can somehow inline as functions (or some other way of getting them out of the tasks list), or any that we don't need anymore.

```
            set-preload  (internal use only) Determines the set of files that  
                         will be preloaded in the HTML file                    
 before-requirejs-build  (internal use only) Do things before the              
                         requirejs:build task                                  
  after-requirejs-build  (internal use only) Do things after the               
                         requirejs:build task     
              requirejs  Runs requirejs optimizer *                            
                 jshint  Validate files with JSHint. *  
               pull-all  Pull all sibling repositories
          string-report  After doing a build, reports on which strings are     
                         missing for each locale that was built.      
```

**Comment by samreid** [comment] 2015-08-11 16:08
@jonathanolson and @samreid will look into the internal use only tasks after the meeting.

set-preload seems like it can be bundled into the before-requirejs-build step

**Comment by samreid** [comment] 2015-08-11 16:10
We decided to get rid of pull-all.

**Comment by jonathanolson** [comment] 2015-08-11 16:10
Can probably get rid of internal tasks by using:
```js
grunt.task.run( 'taskname' );
```
but we'll need to handle it asynchronously. https://github.com/gruntjs/grunt/issues/1184 indicates it might not be possible?

**Comment by samreid** [comment] 2015-08-11 16:11
We decided we can get rid of string-report task.

**Comment by samreid** [comment] 2015-08-11 16:12
We decided to keep the before and after requirejs step.

**Comment by samreid** [comment] 2015-08-12 13:10
I inlined setProload into beforeRequirejsBuild and tested by grunt in hookes law.  Build success, launch success, so I will commit.

**Comment by samreid** [comment] 2015-08-12 13:17
Removed pull-all and string-report above.  Tested by grunt hookes-law and testing grunt --help.  All is well.  Closing.

**Closed by samreid** 2015-08-12 13:17 UTC
