### ISSUE TITLE
Include dependencies.json info in single-file HTML

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/chipper#24] opened 2013-09-03 16:30 UTC

**Comment by pixelzoom** [comment] 2015-01-12 22:26
Are you suggesting that dependency.json should be embedded in the deliverable HTML file?

**Comment by samreid** [comment] 2015-01-13 02:40
I think that is what @jonathanolson was suggesting--that way the dependencies.json cannot get "lost" or separated from the html file it describes.  We may also want to write a tool that can read the dependencies.json file out of an HTML file.

**Comment by pixelzoom** [comment] 2015-05-08 19:28
Duplicate of #135, closing.

**Closed by pixelzoom** 2015-05-08 19:28 UTC
Labels: enhancement
