### ISSUE TITLE
Strings are not loaded for dynamic module

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#879] opened 2020-02-15 23:07 UTC
For https://github.com/phetsims/chipper/issues/844 we would like to load Brands dynamically, like so:

```js
  import( /* webpackMode: "eager" */ `../../brand/${phet.chipper.brand}/js/Brand.js`).then( module => {
  brandProperty.value = module.default;
  } );
```

However, when running that through the chipper build, it failed to find the `joistStrings` which are loaded transitively by brand/phet/js/Brand.js and brand/phet-io/js/Brand.js.  I suspect that the process for harvesting strings during the build doesn't know how to traverse dynamic imports.  Nor am i convinced it should know how to do that.

I'll push a workaround shortly.

**Comment by samreid** [comment] 2020-02-16 14:19
I committed a workaround for this, and would love to hear @jonathanolson thoughts about:

(a) whether this is good enough for our initial migration
(b) whether the string harvesting facility should traverse dynamic module imports in the long run, and if, so, how that might work

**Comment by jonathanolson** [comment] 2020-02-20 18:07
This would be good to discuss in person or on a call. I'd like to know a bit more about how the chipper build process works if this isn't working without a workaround.

**Comment by zepumph** [comment] 2020-02-25 21:32
I was working on this yesterday, and will continue today on it more today. The goal is two fold.

The first is to get ignore plugins working correctly so that other brands are not build into the build. 

The second is to adapt that pattern to try to get a list of "used modules" that includes brands for the string plugin.

**Comment by jonathanolson** [comment] 2020-02-25 21:38
Sounds good, let me know if you want assistance (or for me to tag along in the foreground or background)

**Comment by zepumph** [comment] 2020-02-25 21:54
Above is code that will correctly keep out other brands from builds. This works for the central load point `Brand.js`, as well as any dependency it loads. I mention that potentially obvious statement because a few strategies yesterday that @samreid and I were looking at ignored and dependency loaded by `Brand.js`, but not that module itself. Anywho. . .

From here I will look to see what the current list of "used modules" looks like, and see if we should adapt our in-house `ListUsedModulesPlugin`, or instead try to use the `stats` returned from `compiler.run` in the callback. Yesterday @jonathanolson mentioned that doing the second one is probably better and cleaner so I will start there.

**Comment by zepumph** [comment] 2020-02-26 01:08
After a bit too long of investigation, I found `stats.compilation.fileDependencies` which seems to be the list that we wanted. I tested this by reverting @samreid's work around above in my local copy and then reproducing the joistStrings bug, and seeing it fixed with my above commit.  

I noticed that this `fileDependencies` `Set` has a more files than even `stats.compilation.chunks[0].entryModule._orderedConcatenationList`. The difference holds brand and phet-io repo files when building in phet brand.

Technically this is a list of "files" and not "modules", so I'd love another set of eyes on it. 

@jonathanolson please review. If all is good we can revert @samreid's workaround and push that commit.

**Comment by jonathanolson** [comment] 2020-02-26 01:26
Looks generally good to me. I don't understand the difference between `resourceRegExp` and `contextRegExp`, maybe that would be good to document?

**Comment by zepumph** [comment] 2020-02-26 02:57
Doc added above. This helps chronicle (slightly) the last 2 day of my life. Does it make sense to you?

**Comment by zepumph** [comment] 2020-02-26 17:10
- [ ] We should also revert the above commits:

https://github.com/phetsims/joist/commit/daa45f89e06ce1db7021781830c0267ea7273fcd
https://github.com/phetsims/brand/commit/20315d6830993476dd1d693ce2e526282a472ed9
https://github.com/phetsims/chipper/commit/dc6902a286b71be2ae3b61d96cd38276124e8f4c

**Comment by samreid** [comment] 2020-02-27 02:22
Reverted the changes and tested that links are working in master in phet brand and phet-io brand, and in the migrated code in both brands.  It looks like everything in this issue is complete except for @jonathanolson reviewing the documentation changes.

**Comment by jonathanolson** [comment] 2020-03-05 18:20
Looks great, thanks!

**Closed by jonathanolson** 2020-03-05 18:20 UTC
Labels: chipper:es6-modules, status:ready-for-review
