### ISSUE TITLE
Add flag to Google Analytics message when run embedded

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/chipper#50] opened 2013-12-06 19:04 UTC
Probably investigating frame-busting code to detect whether we are in a frame should be done - then we'll either need to trigger a different URL for Google Analytics, or we need to set an extra variable so that we can track this sort of thing.

**Comment by ariel-phet** [comment] 2016-02-27 02:12
@mattpen can you answer this issue about embedded HTML5 sims...this issue is quite old

**Comment by mattpen** [comment] 2016-03-02 15:35
@jonathanolson - We could presumably use the new custom dimension (simEnvironment) we created to flag if an app is embedded.

We can detect whether we've been embedded in a page by using ```top !== self```.  Should I add this check and flag to the phetcommon GA script?

Also, do we want to track details about where the app is embedded?  ```top.location.href``` would give details about the embedding page.   We could add this to the custom dimension.

**Comment by jonathanolson** [comment] 2016-03-02 16:55
> Should I add this check and flag to the phetcommon GA script?

Sounds good to me.

> top.location.href would give details about the embedding page. We could add this to the custom dimension.

Maybe have simEnvironment just stay as an enumeration, so it would report "embedded", but then have another new dimension that would record "parent frame URL" or something equivalent?

**Comment by mattpen** [comment] 2016-03-09 06:10
@jonathanolson - I added the code to track embedded sims to the phetcommon script tonight.

I also added a 6th custom dimension called `parentFrameLocation` for tracking the embedding party.

I tested this using a require-js built sim both embedded in an iframe and run stand alone. It appears to be working from a locally built sim.

**Comment by jonathanolson** [comment] 2016-03-09 08:06
Looks good, thanks!

**Comment by samreid** [comment] 2016-05-21 04:00
This code:

```js
    else if ( top !== self ){
      // Checks to see if this sim is embedded - phetsims/chipper#50
      phetPageviewOptions.dimension5 = 'embedded';
      phetPageviewOptions.dimension6 = top.location.href;
    }
```
errors out when checking `top.location.href` when running a simulation https, encountered in PhET-iO.  The error is 

```
Uncaught SecurityError: Blocked a frame with origin "https://phet-io.colorado.edu" from accessing a frame with origin "[redacted]". Protocols, domains, and ports must match.
```

When running with the dev tools closed, the sim runs but prints the error.  When dev tools are open, it pauses on the error. (I suppose the latter true only if "pause on error" or equivalent is checked.

@jonathanolson and @mattpen can we discuss how to fix this?

**Comment by samreid** [comment] 2016-05-22 15:36
@kathy-phet serving simulations from https makes it impossible for us to discover the URL of the embedding page (for analytics).  We are currently in a situation where it is trying to get the URL of the embedding page and outputting an error on startup.  Let's discuss how to proceed.

**Comment by mattpen** [comment] 2016-05-23 17:30
@samreid - I changed the request from `top.location.href` to `document.referrer`.  `document.referrer` is attached to the iframe window, so it should be accessible in all circumstances including cross-origin situations.  It is possible to spoof this value by the parent frame, but as the is just for analytics/statistics I think its an acceptable risk.  This change would affect all built sims for phet and phet-io brands.

@jonathanolson - Do you see any problems with this approach?

**Comment by mattpen** [comment] 2016-05-26 20:22
I removed the code to track document.referrer from the guard that checks for embedding, and tested embedding the sim in cross-port, cross-domain, and cross-protocol contexts.  In all cases the sim correctly sent the URL for the parent frame in the documentReferrer dimension.

**Comment by jonathanolson** [comment] 2016-05-27 04:24
@mattpen and @ariel-phet, is this ready for a maintenance release?

**Comment by ariel-phet** [comment] 2016-05-27 15:29
Green light from me, as long as @mattpen says it is ready

**Comment by mattpen** [comment] 2016-05-27 20:35
@jonathanolson - I've checked the code in all permutations of port, domain, and protocol contexts, so I think it is ready for release.

**Comment by samreid** [comment] 2016-06-13 16:15
@jbphet and I are planning to work deploying this fix as maintenance releases tomorrow (Tuesday June 14).

**Comment by jbphet** [comment] 2016-06-14 20:09
List of sims in checklist form for tracking progress on this:

- [ ] acid-base-solutions
- [ ] area-builder
- [ ] arithmetic
- [ ] balancing-act
- [ ] balancing-chemical-equations
- [ ] balloons-and-static-electricity
- [ ] beers-law-lab
- [ ] bending-light
- [ ] build-an-atom
- [ ] color-vision
- [ ] concentration
- [ ] energy-skate-park-basics
- [ ] faradays-law
- [ ] forces-and-motion-basics
- [ ] fraction-matcher
- [ ] friction
- [ ] graphing-lines
- [ ] gravity-force-lab
- [ ] hookes-law
- [ ] isotopes-and-atomic-mass
- [ ] john-travoltage
- [ ] least-squares-regression
- [ ] molarity
- [ ] molecule-shapes
- [ ] molecule-shapes-basics
- [ ] molecules-and-light
- [ ] neuron
- [ ] ohms-law
- [ ] ph-scale
- [ ] ph-scale-basics
- [ ] reactants-products-and-leftovers
- [ ] resistance-in-a-wire
- [ ] trig-tour
- [ ] under-pressure
- [ ] wave-on-a-string

**Comment by jbphet** [comment] 2016-06-14 20:12
I've done the maintenance release process and published RC versions of balancing-chemical-equations through concentration (seven sims total).  @alynne-phet is going to sanity test these sims, and I'll verify that they work when embedded across domains.

**Comment by alynne-phet** [comment] 2016-06-14 21:10
@jbphet Verified on Mac OSX 10.11.5 on chrome and safari

**Comment by jbphet** [comment] 2016-06-15 15:53
Thanks @alynne-phet.  I verified that cross domain embedding works for these 7 sims, so I'll publish and update the checklist above.

**Comment by jbphet** [comment] 2016-06-15 21:05
The fourth batch has been published as RCs, @phet-steele is going to perform sanity testing and verify that cross domain embedding works for all.  The sims in this batch are:

+ energy-skate-park-basics
+ faradays-law
+ forces-and-motion-basics
+ fraction-matcher
+ friction
+ graphing-lines
+ gravity-force-lab
+ hookes-law
+ isotopes-and-atomic-mass
+ john-travoltage
+ least-squares-regression

Once tested and approved, I will publish and will then start the next batch.

**Comment by phet-steele** [comment] 2016-06-15 21:30
@jbphet all tested and approved.

**Comment by jbphet** [comment] 2016-06-16 15:50
Sims from the fourth batch have been published, batch 5 is underway.

**Comment by jbphet** [comment] 2016-06-16 18:50
Batch 5 has now been published as a set of RCs.  The sims are:

+ molarity,
+ molecule-shapes,
+ molecule-shapes-basics,
+ molecules-and-light,
+ neuron,
+ ohms-law,
+ ph-scale,
+ ph-scale-basics,
+ reactants-products-and-leftovers,
+ resistance-in-a-wire,
+ trig-tour,
+ under-pressure,
+ wave-on-a-string

@phet-steele - please test these in the same manner as the previous batch and let me know the result.

**Comment by phet-steele** [comment] 2016-06-16 19:16
@jbphet they all check out!

**Comment by jbphet** [comment] 2016-06-17 16:21
All sims should now be redeployed with this fix.  Since this is the first large-scale maintenance release I've done, and since @phet-steele has a test harness that makes it reasonably easy to verify that a given sim has the fix, I think it would be worth testing that the deployments were all successfully completed.  I talked with @phet-steele and he is willing to do this test.  Assigning to him, he can close if all sims pass the test.

**Comment by phet-steele** [comment] 2016-06-17 20:38
@jbphet all sims have the fix, great job.

**Closed by phet-steele** 2016-06-17 20:38 UTC
Labels: dev:enhancement, dev:phet-io
