### ISSUE TITLE
Make reportMedia.js run without grunt so it can run as a fast precommit hook.

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#964] opened 2020-07-14 00:36 UTC
From Slack:

Sam Reid:house_with_garden:  6:19 PM
CT has a red column with “Fatal error: There is an issue with the licenses for media types.“. Should we add a commit hook for that?

Michael Kauzmann  6:21 PM
It totally bit me last week, and I feel like it caused disruption to a lot of others. I rarely remember to update license.json files. All this to say "yes, that would likely help me!"

Jonathan Olson  6:21 PM
It's presumably not much overhead added when running? If so, it presumably seems helpful

Chris Malley  6:22 PM
A pre-commit hook would be nice.  As long as it doesn't require doing a build, which is currently when media licensing is checked.

Sam Reid:house_with_garden:  6:22 PM
I’m having trouble tracking down this particular problem combo-box-selection.mp3.  Who is trying to load this file?

Jonathan Olson  6:23 PM
Yes, a full build seems a bit expensive

Sam Reid:house_with_garden:  6:23 PM
Maybe something is excluded from my search?

Chris Malley  6:23 PM
Or maybe someone didn't push that mp3 file.
6:24
I see tambo/sounds/combo-box-selection.mp3
6:24
And it has an entry in tambo/sounds/license.json

Sam Reid:house_with_garden:  6:25 PM
Ah, my license.jsons are excluded from search.  The problem is that tambo/sounds/license.json has an entry but the file has been removed

Chris Malley  6:25 PM
Yeah I see that too, after doing a tambo pull.

Sam Reid:house_with_garden:  6:28 PM
Part of what made the rest of the precommit hooks “fast enough” was avoiding the overhead of launching grunt.  To get report-media to work, we would either (a) need to factor it out so it can run without grunt context or (b) just incur the overhead of launching grunt
6:29
For me, grunt --help takes about 1.3 seconds.  I think it’s slower on windows.

Chris Malley  6:31 PM
Maybe we should just remind everyone that, if you're adding/removing media files, you really need to do a local build before pushing.   Or could our pre-commit hook recognize that media files are involved, and do a local build only in that case?

Michael Kauzmann  6:32 PM
It is just the reportMedia function, see CHIPPER/Gruntfile:375

Sam Reid:house_with_garden:  6:32 PM
I removed the license entry and committed to https://github.com/phetsims/sun/issues/602

Michael Kauzmann  6:32 PM
I bet that would be very speedy!

Sam Reid:house_with_garden:  6:32 PM
grunt report-media is sufficient for this class of problems.
6:33
For me, it is
~/apache-document-root/main/tambo$ time grunt report-media
Running "report-media" task
Done.
real	0m1.352s
6:33
Michael how fast is it on your windows?

Michael Kauzmann  6:33 PM
Michael ~/PhET/git/ratio-and-proportion (master)
 $ time grunt report-media
Running "report-media" task
> missing-file: tambo/sounds/combo-box-selection.mp3
Fatal error: There is an issue with the licenses for media types.
real    0m2.565s
user    0m0.045s
sys     0m0.015s
6:33
its all in spinning up grunt.
6:34
running grunt is a total deal breaker.
6:34
(to me)

Sam Reid:house_with_garden:  6:34 PM
OK maybe we can factor out “report media” to run without a grunt
6:34
That’s what we did for lint and that worked out great
New

Michael Kauzmann  6:35 PM
right. I agree it is a slippery slope, but I also don't see a ton of value in grunt.file.exists as opposed to fs.existsSync().
6:35
afk

**Comment by samreid** [comment] 2020-07-14 00:40
To accomplish this, we would need:

* Revise reportMedia.js to no longer use `grunt`
* Revise getPhetLibs.js to no longer use `grunt`
* reportMedia() is an `async` function, and top-level `await` is not yet supported.  We would need a workaround for this.  Possibly an IIFE?  I haven't tried that.

This passed the threshold of "being able to do something useful quickly" for me.  I'll mark it for developer meeting to see if someone else wants to take it on, or if it should be reprioritized, or if we should use another solution, etc.

**Comment by jessegreenberg** [comment] 2020-08-13 19:14
@zepumph mentioned that it may not be too difficult to rewrite to no longer use grunt. There is one part that may be tricky involving using grunt for "recurse".

Others felt that it would be nice but not really worth the effort. CT catches issues like this quickly and we are ready to resolve from that report.

But @samreid mentioned he would be interested in working on this, though it is behind other things in terms of priority right now.

**Comment by samreid** [comment] 2020-08-13 19:14
@zepumph pointed out that we could still use grunt as a dependency, even without loading Gruntfile.js

**Comment by samreid** [comment] 2020-08-15 15:33
@zepumph's idea is working great, and only takes <40ms. I'll commit shortly.

**Comment by samreid** [comment] 2020-08-15 15:39
I tested by removing a license entry from natural selection, then running

```
node ../perennial/js/scripts/hook-pre-commit.js
```

and saw that it failed out properly.

I also tested adding a fake image to wave interference, and tried committing a change and saw that it failed out.

@ariel-phet can you please assign a reviewer to check those 2 commits and run basic tests to make sure this is operating as expected?

**Comment by ariel-phet** [comment] 2020-08-18 19:22
Marking as medium priority (since this looks quick to review), but definitely in the "as time allows" category.

**Comment by pixelzoom** [comment] 2020-08-19 20:52
I'm not familiar with this code, but I don't see any obvious problems in the commits.  And I reproduced @samreid's test results in https://github.com/phetsims/chipper/issues/964#issuecomment-674413603.

Closing.

**Closed by pixelzoom** 2020-08-19 20:52 UTC
Labels: priority:3-medium, status:ready-for-review
