### ISSUE TITLE
Investigate latest javascript (es6/7/8) features to use in non-client facing code. 

### ISSUE THREAD

**Issue by zepumph** [phetsims/chipper#604] opened 2017-08-17 18:16 UTC
From Dev discussion [here](https://github.com/phetsims/phet-io/issues/1169#issuecomment-323148685)

It could be really nice to be able to use new javascript features like `Promises`, `async await`, and chrome headless integration into node into our tools. It could effect places like:
* build tools
* build server
* automated testing 
* statistics
* installer-builder

This will be a good addition to our stack. Chipper 2.0 may be a nice place to begin experimenting with new features. Like trading out large callback trees (like at the end of `git\perennial\js\build-server\build-server.js`) with Promises.

**Comment by samreid** [comment] 2017-10-12 18:20
It was proposed that we investigate adding async await, promises, arrow functions, etc and lint tools in our systems with some simple (non-essential) parts, to see if there will be hassles regarding upgrading node versions or lint tools.

**Comment by samreid** [comment] 2017-10-12 18:26
@mattpen is going to upgrade our phet-server and build-server to later node versions.

**Comment by samreid** [comment] 2017-10-12 18:28
@ariel-phet asked if @zepumph can look into separating out the lint versions so we can use es6+ code in chipper and have it pass lint without letting any es6+ code sneak into sims.

**Comment by zepumph** [comment] 2017-10-12 18:28
In dev meeting today:

@samreid doesn't think this is essential.
@jonathanolson thinks that it will make the code much simpler, and may not be too complicated.

@ariel-phet wants to emphasize importance of "it should supply a benefit, not just a bell or whistle"


@samreid to prototype, we should use async await in one place, like a fake part of chipper. From there we can get environments up to speed (updating npm, node) make sure lint, make sure that this works on bayes/phet-server.
Here is a link to the LTS support of node https://github.com/nodejs/Release#release-schedule1.

Currently I see on bayes:
```
[mika5203@bayes ~]$ node --version
v6.9.1
[mika5203@bayes ~]$ npm --version
3.10.8
```
Assigning to @mattpen 


@samreid - promises/async await is not the only thing. There are arrow functions, `let` and `const`, `class` keyword, and other stuff. Perhaps we should opt in to certain features one at a time. There are so many features!!! We don't want a lot of overhead in different syntax.

Starting out with @mattpen with making sure that node/npm versions are up to date on bayes and phet-server.

We also want @zepumph to look into splitting out the lint rules so that chipper/build code can be in es6+, but our sim code stays with es5.

**Comment by zepumph** [comment] 2017-10-12 18:29
@ariel-phet says in the next few weeks.

**Comment by mattpen** [comment] 2017-11-03 17:45
Node and NPM have been updated on phet-server, phet-server-dev, and bayes.  We should now be able to use these features on the server side if we so choose.

**Comment by mattpen** [comment] 2017-11-03 17:45
@zepumph @samreid - should we close this issue?

**Comment by samreid** [comment] 2017-11-03 18:39
Let's leave this issue open, the next steps will be to try out some ES6 features or async/await and make sure all developers can use them.

**Comment by zepumph** [comment] 2017-11-15 20:34
I'm working in a branch on chipper called 'es6'.

I think that we will be able to specify a certain folder as es6 for IDEA:
https://blog.jetbrains.com/webstorm/2017/08/how-to-configure-code-completion-in-full-stack-javascript-projects/
Here is an issue in youtrack that shows people would really like an easy fix to this problem. https://youtrack.jetbrains.com/issue/WEB-12666

My game strategy:
- [x] Create a simple grunt task that uses es6
- [ ] Make sure that normal lint processes don't break because of the above check
- [ ] make sure that we can lint that es6 code
- [ ] make sure that IDEA doesn't complain about that es6 code

Right now I am putting all of thes6 code into `chipper/js/grunt/es6`.

**Comment by zepumph** [comment] 2017-11-15 22:27
I have rethought the names of this process as really an exercise in pursuing features up through es8, since that is async await, so I renamed everything to es8 so that it is obvious that the eslint parser can handle up to ecmaVersion: 8.

There are a few things that I have done to my IDEA in order for this to work in Webstorm. The above youtrack https://youtrack.jetbrains.com/issue/WEB-12666 is exactly our problem, and it is fixed in 2017.3, which is currently in EAP (released early Dec).

I downloaded that and found that you can now dictate what javascript language level you want as your global level, as well as define specific levels for scopes. See the screen shot below:
![image](https://user-images.githubusercontent.com/6856943/32863260-583d4b28-ca07-11e7-9639-dad2e864236c.png)


Notice the impeccable sun outlining the new triple-dot menu that allows you to specify scopes as needed. This works well, and formatting and underlining misspellings is as expected. 

The **one issue** we have found is that for those devs that have eslint integrated into their IDEA, this does not yet have support for scoping out different eslintrc files to use. As a result you still get es5 lint error underlines in the es6+ files. @samreid and I talked about solutions for this, and we found three potential medium-bad solutions:
  * Manually change the eslintrc file in the same project each time you want to edit es6+ files.
  * Create another project for developing es6+ so you can specify all your tools as needed.
  * Just deal with the eslint highlighting problems in the same project.



I still haven't researched es6's new way of loading modules/imports. Does it work well for node? So that is to come.

**Comment by zepumph** [comment] 2017-11-15 22:29
Helpful eslint links as we work on this more:
All of the rules (including the special ones for es6) https://eslint.org/docs/rules/
Configuring guide - https://eslint.org/docs/user-guide/configuring

**Comment by jonathanolson** [comment] 2017-11-16 05:36
I'd definitely be excited about using ES6 features in perennial. Didn't see an easy way to change our linting either (to have only some parse as ES6), so I had to revert some planned usage of features.

**Comment by samreid** [comment] 2017-11-16 05:37
@zepumph is working on a way to segregate our linting into an ES5 linting step and an ES6 linting step.

**Comment by samreid** [comment] 2017-11-16 16:32
By the way, we may wish to consider moving our simulation codebase to ES6.  We do most of our requirejs testing in ES6 compatible browsers, and we already require a build step for our builds anyways--we could tack on a ES6->ES5 transpile step.  But let's start with chipper and see how it goes.

**Comment by zepumph** [comment] 2017-11-16 20:08
>But let's start with chipper and see how it goes.

By "chipper" do you also mean perennial?

**Comment by samreid** [comment] 2017-11-16 20:17
Yep

**Comment by mattpen** [comment] 2017-11-16 21:09
I just made a change in chipper using ES6 features, https://github.com/phetsims/chipper/commit/504a620f9568205cf0b014600d99ce830e98ec78 (line 85).  Is this ok?

**Comment by zepumph** [comment] 2017-11-16 21:20
From slack conversation:
```
@jonathanolson said:
>I’m definitely interested. Do you feel like it would be ready for mainly a code review and could be merged into master?


I do think that. Right now the linting is based on directories, so it will only work if all the es6 code is in it's own folder in perennial


[12:16] 
From there you just have to exclude that folder in the es5 lint task, and add that folder to the es6 one.


Jonathan Olson [12:16] 
I think all of perennial should be suitable to be at least es6+


Michael Kauzmann [12:16] 
Ok.


[12:17] 
We can exclude perennial from es5 linting, and just es6 lint it.


[12:17] 
Depending on the approach we have moving forward for es6 strictness, there may be some updating to be had. For example getting rid of "var" for "let/const"


[12:17] 
but very doable.


[12:19] 
@jonathanolson would you like to code review https://github.com/phetsims/chipper/issues/604 and see if master is the next step? Do you have time for that?


[12:19] 
Also good to note that "es6" is actually es8, async await is supported with the linter.


Jonathan Olson [12:19] 
Yes, will review.


[12:19] 
understood!
```

So @jonathanolson will code review the above commits, see if it is good for master, and we will go from there.

**Comment by zepumph** [comment] 2017-11-16 21:33
I added perennial to the es8 linting instead of es5. From here @jonathanolson can code review for perennial and the specific chipper es8 directory. Take it away!

**Comment by zepumph** [comment] 2017-11-16 21:35
He also mentioned that a nice way to manage eslintrc files will be on a per directory basis, see https://github.com/eslint/eslint/issues/2026 for deets. I will look into this next.

**Comment by zepumph** [comment] 2017-11-16 21:39
I pushed this branch to master. Linting is still working as expected, and workflow shouldn't change for general phet development.

**Comment by pixelzoom** [comment] 2017-11-16 22:23
I have not updated to Node8 and NPM5, but the info above seems to indicate that I only need to do that if I’m curious about ES8 features.

After pull-all.sh, ‘grunt lint’ in any repo is failing:

```
% cd equality-explorer
% grunt lint
Loading "Gruntfile.js" tasks...ERROR
>> SyntaxError: Unexpected token function
```

Next I installed node v8.9.1 and npm 5.5.1 (LTS release).  ‘grunt lint’ now succeeds for sim repos.  ‘grunt lint’ for chipper fails:

```
% grunt lint
Running "lint" task

/Users/cmalley/PhET/GitHub/chipper/js/grunt/deployProduction.js
  85:26  error  Parsing error: Unexpected token ,

/Users/cmalley/PhET/GitHub/chipper/js/grunt/es8/testES8.js
  12:3  error  Parsing error: The keyword 'let' is reserved

✖ 2 problems (2 errors, 0 warnings)
Fatal error: 0 Lint Errors
```

**Comment by pixelzoom** [comment] 2017-11-16 22:26
`grunt` is also failing for sims, e.g.:

```
grunt 
Running "lint-all" task

/Users/cmalley/PhET/GitHub/chipper/js/grunt/deployProduction.js
  85:26  error  Parsing error: Unexpected token ,

✖ 1 problem (1 error, 0 warnings)
Fatal error: 0 Lint Errors
```

Why does a local build involve deployProduction.js?

**Comment by samreid** [comment] 2017-11-16 22:32
Same problem here running node v8.3.0

**Comment by samreid** [comment] 2017-11-16 22:32
> Why does a local build involve deployProduction.js?)

It's probably just getting loaded in a require statement and never called.

**Comment by samreid** [comment] 2017-11-16 22:33
A reminder that some chipper files (at least initialize-globals.js) needs to remain ES5

**Comment by pixelzoom** [comment] 2017-11-16 22:36
I believe that getVersionForBrand.js and everything in chipper/js/requirejs-plugins/ also needed to remain ES5 compliant.  And lint needs to verify ES5 compliance for all chipper files that need to be ES5 compliant.

**Comment by mattpen** [comment] 2017-11-16 22:41
I fixed this error:
```
/chipper/js/grunt/deployProduction.js
  85:26  error  Parsing error: Unexpected token ,
```
in this commit: https://github.com/phetsims/chipper/commit/057324e03e5beaa1a6299e92c977db17350d1179.

**Comment by pixelzoom** [comment] 2017-11-16 22:44
An additional problem is what to do about package-lock.json. Slack discussion:

@pixelzoom WebStorm is also telling me I need to add package-lock.json for all dirs where I did `npm install`. What is the plan for package-lock.json? gitignore it? check it in?

@jonathanolson There’s a deferred issue that basically says we should run “npm config set save false” to avoid creating them for now and in the future we can consider using them

@samreid The issue is `https://github.com/phetsims/chipper/issues/578`

@pixelzoom I guess that issue can’t be deferred anymore :)

**Comment by pixelzoom** [comment] 2017-11-16 23:11
Slack:

Jonathan Olson [4:04 PM] 
Ok, chipper master should be fixed up a bit. chipper/js/grunt and perennial/js currently support more JS features


Sam Reid [4:05 PM] 
So can we rely on developers having ES8 installed, or ES8 limited to non-production code for now?  developers (and servers)


Chris Malley [4:06 PM] 
What happened to `grunt es8Test` ?  Not sure what was fixed because I don’t see any commits associated with the issue, https://github.com/phetsims/chipper/issues/604

**Comment by jonathanolson** [comment] 2017-11-16 23:15
I switched things to per-directory .eslintrc files (described in https://github.com/eslint/eslint/issues/2026). This allowed reverting some of the es6/es8 branch changes, and simplifying a few things.

@zepumph can you review my recent commits to chipper?

**Comment by pixelzoom** [comment] 2017-11-16 23:17
Re es8Test ... In Slack, @jonathanolson said:
> I removed it. We don’t particularly need a file whose sole existence is to test the linter (with a full directory of its own)

**Comment by samreid** [comment] 2017-11-17 00:37
I sent this email to the dev mailing list:

Hello PhET Development Team,

As part of our upgrade to ES8 in non-simulation code, the build tools will require Node 8.9.1 LTS or higher starting on Monday Nov 20 at 11am.  Please see https://github.com/phetsims/chipper/issues/604 for details.

Best Regards,
Sam

**Comment by zepumph** [comment] 2017-11-17 00:42
@samreid how does it not require this right now?

**Comment by samreid** [comment] 2017-11-17 01:47
Good point, it probably does!

**Comment by jonathanolson** [comment] 2017-11-22 00:17
Promises and async/await are super helpful. Here is a notable before/after:

before:
```js
/**
 * Checks out master for a repository and all of its dependencies.
 * @public
 *
 * @param {string} repo - The repository name
 * @param {boolean} includeNpmUpdate - Whether npm updates should be done to repositories.
 * @param {Function} callback - callback(), called when done
 * @param {Function} [errorCallback] - errorCallback( code: {number}, stdout: {string} ), called when errors with the
 *                                     exit code of the process.
 */
module.exports = function( repo, includeNpmUpdate, callback, errorCallback ) {
  winston.info( 'checking out master for ' + repo );

  getDependencies( repo, function( dependencies ) {
    // Ignore the repo we just checked out, and the comment
    var repoNames = Object.keys( dependencies ).filter( function( key ) {
      return key !== 'comment' && key !== repo;
    } );

    // async loop until done
    function checkoutNext() {
      if ( repoNames.length ) {
        var dependencyRepoName = repoNames.shift();

        gitCheckout( dependencyRepoName, 'master', function() {
          checkoutNext();
        } );
      }
      else {
        gitCheckout( repo, 'master', function() {
          if ( includeNpmUpdate ) {
            npmUpdate( repo, function() {
              npmUpdate( 'chipper', function() {
                callback();
              }, errorCallback );
            }, errorCallback );
          }
          else {
            callback();
          }
        }, errorCallback );
      }
    }

    checkoutNext();
  }, errorCallback );
};
```

after:
```js
/**
 * Checks out master for a repository and all of its dependencies.
 * @public
 *
 * @param {string} repo - The repository name
 * @param {boolean} includeNpmUpdate - Whether npm updates should be done to repositories.
 * @returns {Promise}
 */
module.exports = async function( repo, includeNpmUpdate ) {
  winston.info( 'checking out master for ' + repo );

  var dependencies = await getDependencies( repo );

  // Ignore the repo we just checked out, and the comment
  var repoNames = Object.keys( dependencies ).filter( function( key ) {
    return key !== 'comment' && key !== repo;
  } );

  // TODO: can we use each here safely?
  for ( var i = 0; i < repoNames.length; i++ ) {
    await gitCheckout( repoNames[ i ], 'master' );
  }

  await gitCheckout( repo, 'master' );

  if ( includeNpmUpdate ) {
    await npmUpdate( repo );
    await npmUpdate( 'chipper' );
  }
};
```

Since this is integrated and linting well, is there anything else to do for this issue? Should we think about converting all possible code to use promises instead?

Additionally, is there a good way to document the types used for a Promise's resolve/reject?

**Comment by samreid** [comment] 2017-11-22 16:33
Thanks for showing the diff @jonathanolson, that looks great.  It would be very time consuming to review every file of chipper to evaluate converting to ES6 idioms (such as arrow functions, async await, etc., const), but until we do we will have a mishmash of ES5/ES6.  My inclination is to live with the mishmash and just update incrementally as we see fit, but I can see the arguments either way.

**Comment by zepumph** [comment] 2017-11-22 18:41
I think that mishmash is the best approach for now, partially because we as a team haven't figured out what we want our es6+ idioms/code style to be. I could see us working through chipper2.0 as an experimentation time, and then reconvening after to discuss what people want to standardize as phet practice moving forward.

**Comment by samreid** [comment] 2017-11-22 18:49
@zepumph that sounds great to me.

**Comment by zepumph** [comment] 2017-11-22 18:50
Part of what we should be thinking about are es6 lint rules we want to add to the necessary directories.

**Comment by samreid** [comment] 2017-11-24 03:51
I was thinking of iterating through chipper and converting to const/arrow functions/new options pattern, etc when I recalled @jonathanolson said he would be working on things in branches for chipper 2.0.  Rather than create a messy merge, I'll wait.  I'm adding this comment in case others are thinking along the same lines.

**Comment by pixelzoom** [comment] 2017-11-26 18:06
Self assigning so that I remember to review comments on this issue that occurred since 11/17/17.

**Comment by pixelzoom** [comment] 2017-11-27 18:09
Finished reviewing comments.    I'm on the fence about whether https://github.com/phetsims/chipper/issues/604#issuecomment-346737745 is worth the effort, but will let others make that call.

**Comment by samreid** [comment] 2017-11-27 18:23
The chipper 2.0 branch is already making good use of ES6 features, it seems like a step in the right direction.

**Comment by pixelzoom** [comment] 2017-12-31 18:20
FYI... WebStorm 2017.3 now supports multiple JavaScript versions in a project. 

From https://www.jetbrains.com/webstorm/whatsnew:
> **Multiple JavaScript versions in a project**
If your project uses different versions of JavaScript and you want WebStorm to complain when the ES6 or JSX syntax is used in the ECMAScript 5.1 file, you can now configure JavaScript language versions per directory in *Preferences | Languages & Frameworks | JavaScript*.

**Comment by samreid** [comment] 2018-01-01 16:57
Works great, thanks @pixelzoom.  I configured chipper/ perennial/ and rosetta/ for ES6.

**Comment by pixelzoom** [comment] 2018-01-05 22:32
@samreid said:
>  I configured chipper/ perennial/ and rosetta/ for ES6.

I this the complete list of repos that are using ES6+ features?

**Comment by samreid** [comment] 2018-01-05 22:37
A search for `await` gave the preceding list.  A search for `const` indicates installer-builder should probably be on the list too.

**Comment by ariel-phet** [comment] 2018-01-08 17:16
What repos/directories will have ES6+ features:

All perennial, rosetta, yotta, installer-builder, aqua, smithers (pretty much any server side code) 

Directories in chipper:
js/grunt

**Comment by ariel-phet** [comment] 2018-01-08 17:19
@zepumph suggests a file in perennial marking which repos/directories include these features, or perhaps a file about setting up your dev environment.

Perhaps something in phet-info? @pixelzoom said he could move some relevant files into https://github.com/phetsims/phet-info/tree/master/ide

**Comment by pixelzoom** [comment] 2018-01-08 18:45
Based on https://github.com/phetsims/chipper/issues/604#issuecomment-356031704, perennial/data/es6-repos contains:

```
aqua
chipper/js/grunt/
installer-builder
perennial
rosetta
smithers
yotta
```

**Comment by pixelzoom** [comment] 2018-01-08 18:50
To configure in WebStorm 2017.3+, go to _Preferences | Languages and Frameworks | JavaScript_:

![screenshot_461](https://user-images.githubusercontent.com/3046552/34686771-e8ca29fe-f469-11e7-8d28-9ef3c617001f.png)

Click the `…` button to the right of the version number combo box.  Then fill in the "JavaScript Language Versions" dialog to look like this:

![screenshot_462](https://user-images.githubusercontent.com/3046552/34686832-14eec4ea-f46a-11e7-8327-2dcfdfb725f0.png)

**Comment by samreid** [comment] 2018-01-08 18:53
Done, thanks!

**Comment by pixelzoom** [comment] 2018-01-08 19:00
Configuring IDEA is apparently different, and only supported in Ultimate Edition (UE).  Since I don’t have UE, I can’t complete the setup instructions in https://github.com/phetsims/phet-info/blob/master/ide/idea/setup.md.   Can I get a volunteer who is using IDEA UE to take over?

**Comment by pixelzoom** [comment] 2018-01-08 19:34
I asked @oliver-phet who has IDEA licenses, then randomly chose someone:

```
> _.shuffle( [ 'JO', 'JB', 'DB', 'MP' ] )[ 0 ]
"JB"
``

@jbphet is the lucky winner.

**Comment by jbphet** [comment] 2018-04-03 19:31
Instructions for adding ES6 support to IDEA Ultimate Edition were already in the document, but it didn't include some important information about the version of IDEA that is needed, so I made some updates and did some editing.  This is done, closing.

**Closed** 2019-11-18 18:29 UTC
Labels: chipper:2.0
