### ISSUE TITLE
Make `grunt update` (and its subtasks) responsible for `git add` when it creates files.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#1256] opened 2022-05-25 23:47 UTC
In https://github.com/phetsims/tambo/commit/382620e4ce6996491b6b24fead907762fd081d51, new mp3 files were pushed. But their corresponding mp3.js (modulify) files were not added and were therefore not pushed.  It worked for the developer, because he had the mp3.js files in his working copy.  But it failed CT, and (after doing a pull-all.sh to get some other unrelated fixes) I had to fix it before I could continue with my work.

This is not the first time this has happened, because it's easy to forget to manually do the `git add`. 

If the mp3.js file did not previously exist in git, then perhaps `grunt modulify` should be responsible for the `git add`.

**Comment by chrisklus** [comment] 2022-06-16 17:56
From 6/16/22 dev meeting:

JG: Is there a need for modulifying when prototyping? When we wouldn't want to `git add`.
JB: Yes, I do use this case sometimes but have no objection to auto-adding.
CM: We could add an option like `--no-add` to opt out of automatically git adding.
SR: Should this apply to grunt update as well?

Yes, we think grunt update should auto-add too. We also think the no-add option is not necessary to include for now until someone wants to add it in the future.

SR note for implementer: We should probably make a  function for writing files and adding them, since this will be needed in a few places.

@jessegreenberg volunteered to take a look, thanks!

**Comment by pixelzoom** [comment] 2022-06-16 17:59
I'll change the title of this issue to reflect what we've decided to do.

**Comment by jessegreenberg** [comment] 2022-06-20 22:25
`grunt update` and its subtasks are adding files to git if they are unclean. I found I had to `await` a few tasks that weren't previously using that or else git would lock up with a .git/index.lock file. Over slack a few devs confirmed that chipper can depend on perennial-alias so I used common code from there.

@jonathanolson can you please review this since you are listed as an author of chipper's gruntfile and modulify.js?

**Comment by samreid** [comment] 2023-04-12 19:35
This has been working well for a long time. I reviewed the commits and do not have any recommendations, closing.

**Closed by samreid** 2023-04-12 19:35 UTC
Labels: status:ready-for-review
