### ISSUE TITLE
How to test dynamic locale in sims that have no translations?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#1319] opened 2022-08-30 01:57 UTC
I've been adding support to various sims for dynamic locale.  Those sims have been published, so translations exist.  How do we test sims that have not been translated, and have no translations? What support is needed? 

geometric-optics-basics is an immediate example, included in https://github.com/orgs/phetsims/projects/44.  Luckily, only its title is specific to that sim, and everything else comes from geometric-optics, which does have translations.

**Comment by jonathanolson** [comment] 2022-09-01 16:39
`phet.chipper.setAllStrings( '...' )` and studio have been the most useful for me, although I've also manually adjusted strings phet-brand with `phet.someSim.someSimStrings.someStringProperty.value = '...'`.

**Comment by zepumph** [comment] 2022-09-08 18:34
I trust @jonathanolson on whatever he would like to implement. My main hopes are that it is easy to get back to a test case where you witnessed a bug. If there is a "random strings" mode, then perhaps being able to copy that into a query string to relaunch would be ideal. 

I also like the idea of using the same string test values/modes we already have, but cycling through them dynamically.

**Comment by pixelzoom** [comment] 2022-09-08 18:39
> I also like the idea of using the same string test values/modes we already have, but cycling through them dynamically.

+1

**Comment by pixelzoom** [comment] 2022-09-13 22:20
This issue blocks further work on https://github.com/phetsims/models-of-the-hydrogen-atom/issues/39.  MOTHA is a new sim with no translations, so I can't identify layout problems, or prevent new problems.

**Comment by pixelzoom** [comment] 2022-11-05 14:49
This is impacting more than sims that have no translations. In many math sims, symbols are translatable,  but are seldom (or possibly never) translated.   So after adding support for dynamic locale, I'm spending a lot of time pressing Ctrl-i, trying to cycle through a translation that may have translated a specific math symbol, and often finding none -- which mean not testing adequately.  That also means that QA can't test adequately.

So I'm writing new sims that I can't test at all. I'm converting existing sims that that I can't test adequately. QA can't really be certain that they are testing any sim adequately for dynamic locale. And we're supposed to do this for all sims. 

This has been high prioirty for almost 2 month, and there has been no progress. That's no fault of @jonathanolson -- it's a project management problem. So unfortunately, I'm going to move this back to the "To be discussed" column of the Developer Meeting project board, so that we can discuss how this should be prioritized and managed.

**Comment by samreid** [comment] 2022-11-10 18:45
Patch from dev meeting:

<details>

```diff
Index: js/getStringModule.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/getStringModule.ts b/js/getStringModule.ts
--- a/js/getStringModule.ts	(revision 05c66c8da184a50129996bb093d5444f50eb06bc)
+++ b/js/getStringModule.ts	(date 1668105694695)
@@ -26,10 +26,34 @@
 // Holds all of our localizedStrings, so that we can save our phet-io string change state
 export const localizedStrings: LocalizedString[] = [];
 
+if ( phet.chipper.queryParameters.dev ) {
+  window.addEventListener( 'keydown', ( event ) => {
+    if ( event.key === 'p' ) {
+      localizedStrings.forEach( localizedString => {
+        // const length = Math.round( Math.random() * 20 ) + 2;
+        localizedString.property.value = localizedString.property.value + localizedString.property.value;
+      } );
+    }
+    if ( event.key === 'm' ) {
+      localizedStrings.forEach( localizedString => {
+        // const length = Math.round( Math.random() * 20 ) + 2;
+        localizedString.property.value = localizedString.property.value.substring( 0, localizedString.property.value.length / 2 );
+      } );
+    }
+    if ( event.key === 'r' ) {
+      localizedStrings.forEach( localizedString => {
+        const length = Math.round( Math.random() * 20 ) + 2;
+        localizedString.property.value = ( '' + Math.random() + '' + Math.random() + '' ).substring( 0, length );
+      } );
+    }
+  } );
+}
+
 // For developer internal use, similar to the stringTest query parameter
 window.phet.chipper.setAllStrings = ( str: string ) => {
   localizedStrings.forEach( localizedString => {
-    localizedString.property.value = str;
+    // const length = Math.round( Math.random() * 20 ) + 2;
+    localizedString.property.value = localizedString.property.value + localizedString.property.value;
   } );
 };
 

```

</details>

@pixelzoom said that design is reasonable and better than we have now.  @marlitas and @samreid volunteered to bring it to production and add it to the QA handbook.

**Comment by jbphet** [comment] 2022-11-10 18:51
We discuss this during the 11/10/2022 dev meeting, and @samreid created a quick demo that seemed like a reasonable next step.  He and @marlitas will implement it.  One of the requirements will be to make it reproducible when using random values.  Once this is implemented, it will be assigned to @pixelzoom for testing and review.

**Comment by samreid** [comment] 2022-11-11 17:06
Today @marlitas and I wrote a working draft for this and it seems to be working well.  The key commands are described in initialize-globals:

stringTest=dynamic:

adds global hotkey listeners to change the strings.
  right arrow - doubles a string, like string = string+string
  left arrow - halves a string
  up arrow - cycles to next stride in random word list
  down arrow - cycles to previous stride in random word list
  spacebar - reset to initial english strings, and resets the stride

@pixelzoom this is ready for use in development.

@marlitas will additionally look into using KeyboardListener and adding it to the display via `addInputListener`.  Thanks!  After that, it will be ready for review.

**Comment by pixelzoom** [comment] 2022-11-11 17:13
Reminder to document the final solution in the QA Book, and notify @KatieWoe.

**Comment by pixelzoom** [comment] 2022-11-11 22:38
Some problems with this commit https://github.com/phetsims/joist/commit/2663d3d300561728ac3b398a9beccb9e3044dbb8

(1) `function setStride` is defined inside the event listener. So every time we get an event, we're reallocating this function. It should be moved outside the listener.

(2) The are 5 `if` statements, and no `else`.  So all 5 `if` expression are evaluated for every event.  Use `if else` logic.

**Comment by pixelzoom** [comment] 2022-11-11 22:44
Some thing that I reported in Slack#dev-public:

(1) If you press left arrow enough times, it results in an empty string, which it probably should not do — there should be a minimum length of 1.  And then pressing right arrow has no affect, because doubling an empty string results in an empty string.

(2) This approach is apparently chopping up pattern strings, with some very strange (and not very useful) results. Ideally it shouldn't touch pattern strings. See for example Fourier.  Here's a piece of the control panel in the Discrete screen before pressing any keys:

<img width="285" alt="screenshot_1950" src="https://user-images.githubusercontent.com/3046552/201440375-c90e2e05-9364-42a6-9252-1e4b9892ddfa.png">

Here it is after pressing left arrow once:

<img width="280" alt="screenshot_1951" src="https://user-images.githubusercontent.com/3046552/201440397-e04ebb89-b1e1-4a1e-8fce-15bb123807b8.png">

So this results in invalid pattern string, which could not possibly be entered via Rosetta.  Also note that `“space & time ({{spaceS”` is now _longer_ than the original string, not shorter.

(3) There seems to be something wrong with the left-arrow "cut the length in half" algorithm.  For example, in Fourier I see "Discrete" -> "Disc" -> "D".   That last string should be "Di".

(4) We quickly lose any resemblance to the orignal string.  For example in Fourier's Discrete screen:

original string: Harmonics
left arrow: Harm
left arrow: H
right arrow: HH
right arrow: HHHH
right arrow: HHHH

More useful behavior would be relative to the original string:

original string: Harmonics
left arrow: Harm
left arrow: Ha
right arrow: Harm
right arrow: Harmonics
right arrow: HarmonicsHarmonics

**Comment by marlitas** [comment] 2022-11-14 03:35
Strings will no longer empty, however the quirky halving is a bit trickier. There are directional codes embedded in the string and I need to figure out how to properly strip these out. My regex explorations have so far only succeeded in stripping out the first code at the beginning of the string and not the one at the end. I'm hoping @jbphet will be able to help me figure this one out.

**Comment by marlitas** [comment] 2022-11-16 03:46
With some help from @jbphet (Thanks!), I was able to remove directional unicode from the strings. Halving should now behave properly.

**Comment by pixelzoom** [comment] 2022-11-18 00:19
Unassigning. Let me know when this is ready for another review or test-drive.

**Comment by marlitas** [comment] 2022-11-28 03:42
Here's a very messy patch for my own uses to work around pattern strings.

<details>

```diff
Index: js/DynamicStringTest.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/DynamicStringTest.ts b/js/DynamicStringTest.ts
--- a/js/DynamicStringTest.ts	(revision 23a31d370e98814a6e32b914ac74964606b7df86)
+++ b/js/DynamicStringTest.ts	(date 1669606606922)
@@ -32,6 +32,75 @@
       } );
     }
 
+    function stripPatternString( string: string ): string {
+      // split string by character
+      const characters = string.split( '' );
+      let count = 0;
+      let isOn = true;
+      let frontBraceCount = 0;
+      let backBraceCount = 0;
+
+      characters.forEach( character => {
+        // turn counter off if there are two {{ in a row
+        if ( character === '{' ) {
+          frontBraceCount++;
+          if ( frontBraceCount === 2 ) {
+            isOn = false;
+            frontBraceCount = 0;
+          }
+        }
+
+        // turn counter on if there are two }} in a row
+        else if ( character === '}' ) {
+          backBraceCount++;
+          if ( backBraceCount === 2 ) {
+            isOn = true;
+            backBraceCount = 0;
+          }
+        }
+
+        if ( isOn ) {
+          count++;
+        }
+      } );
+
+      // divide count by two
+      const splitLength = count / 2;
+      isOn = true;
+      frontBraceCount = 0;
+      backBraceCount = 0;
+
+      // stop slice once we reach the half count
+      for ( let i = 1; i <= splitLength; i++ ) {
+        // start at end of array
+        const character = characters[ characters.length - i ];
+
+        // turn slice off if there are two }} in a row
+        if ( character === '}' ) {
+          backBraceCount++;
+          if ( backBraceCount === 2 ) {
+            isOn = false;
+            backBraceCount = 0;
+          }
+        }
+
+        // turn slice on if there are two {{ in a row
+        else if ( character === '{' ) {
+          frontBraceCount++;
+          if ( frontBraceCount === 2 ) {
+            isOn = true;
+            frontBraceCount = 0;
+          }
+        }
+
+        if ( isOn && character !== '{' || character !== '}' ) {
+          characters.splice( characters.length - i - 1, 1 );
+        }
+      }
+
+      return characters.join( '' );
+    }
+
     window.addEventListener( 'keydown', event => {
 
       // check if the keyboard event is a right arrow key
@@ -48,11 +117,14 @@
           // Strip out all RTL (U+202A), LTR  (U+202B), and PDF  (U+202C) characters from string.
           const strippedString = localizedString.property.value.replace( /[\u202A\u202B\u202C]/g, '' );
           const stringLength = Utils.toFixedNumber( strippedString.length / 2 + 1, 0 );
+
+          strippedString.includes( '{{' ) || localizedString.property.value.includes( '}}' ) ?
+          localizedString.property.value = stripPatternString( strippedString ) :
           localizedString.property.value = localizedString.property.value.substring( 0, stringLength );
         } );
       }
 
-      // Check if the user press the spacebar
+      // Check if the user pressed the spacebar
       else if ( event.keyCode === 32 ) {
         stride = 0;
         console.log( 'stride = ' + stride );
```

</details>

**Comment by marlitas** [comment] 2022-12-08 18:59
@pixelzoom this is now ready for review and further test driving.

It seems that the work done so far is no longer blocking for working on sims with no translations. Removing the priority label.

**Comment by pixelzoom** [comment] 2022-12-11 17:13
Very nice! These are huge improvements, thanks for doing this.

I noticed a few things that are worth mentioning. I don't if they need to be addressed, or maybe just clarified in documentation -- @marlitas your call.

---

(1) Buggy (?) support for string patterns.

The current string patterns used named placeholders, as implemented by `StringUtils.fillIn`. For example, in Fourier we have:

```
  "spaceSymbol": {
    "value": "space ({{symbol}})"
  },
```

... which looks like this in the control panel of the _Discrete_ screen:

<img width="238" alt="screenshot_2039" src="https://user-images.githubusercontent.com/3046552/206917507-a3b3bc64-adb7-4d81-9cbc-b8e43d4a9e74.png">

With `stringTest=dynamic` and one press of the RIGHT arrow, I expected to see "space (x)space(x)".  But instead I see:

<img width="250" alt="screenshot_2040" src="https://user-images.githubusercontent.com/3046552/206917561-bc33243a-ecdc-44ea-9c8c-f9afe1ed57c6.png">

And then pressing the LEFT arrow, I'd expect to see the original string, "space (x)". But instead I see:

<img width="228" alt="screenshot_2041" src="https://user-images.githubusercontent.com/3046552/206917595-a47075d4-3fb4-4cf5-9ba5-a5a029781da0.png">

Maybe this is the intended behavior, and I just don't understand how you're supporting placeholders. Or maybe it's buggy.

---

(2) No support for older string pattern.

Older sims used a string pattern based on numeric placeholders (not named placeholders), implemented in `StringUtils.format`. For example, in Beer's Law Lab we have:

```
  "pattern.0value.1units": {
    "value": "{0} {1}"
  },
```

... which is displayed  in the _Beer's Law_ screen like this:

<img width="274" alt="screenshot_2037" src="https://user-images.githubusercontent.com/3046552/206917309-6bec335a-3936-45fb-ac54-f7f9bb0a1f22.png">

With `stringTest=dynamic` and one press of the LEFT arrow, this becomes:

<img width="275" alt="screenshot_2038" src="https://user-images.githubusercontent.com/3046552/206917343-385ee05d-679b-499b-8a08-f4ed71ad8cb8.png">

Since this form of string pattern is deprecated, maybe this is fine.  But beware that many sims still use this pattern, and will continue to do so because we can't easily change translated strings.

---

(3) Some strings require multiple arrow presses before they will shrink/grow.

Example in Beer's Law Lab...  The _Beer's Law_ screen has this ruler, with units in "cm":

<img width="292" alt="screenshot_2042" src="https://user-images.githubusercontent.com/3046552/206917814-8ee2fd10-660c-41a2-b836-91e2dcd291b1.png">

Follow these steps after starting the sim with `stringTest=dynamic`:

1. Press the LEFT arrow 3x before "cm" shrinks to "c".
2. Press RIGHT arrow once to change "c" to "cm".
3. Press RIGHT arrow 3x to change "cm" to "cmcm".

This behavior seems very odd. Bug? Or something that needs to be documented?

---

**Comment by pixelzoom** [comment] 2023-01-17 23:53
> (2) Buggy (?) support for string patterns.

This came up today while @KatieWoe was testing ESP.  It caused a bit of confusion.  @marlitas are there plans to do something special for patterns, or should we plan on living with the current behavior?  If the latter, it would be good to communicate to QA.

**Comment by marlitas** [comment] 2023-01-20 17:37
I think we should plan on living with the current behavior. I'm not sure the effort to address that is a worthy return on investment. Right now we're stripping out the string pattern and doubling it at the end, rather than addressing the logic to remember it's original placement in the string. This logic gets especially tricky when we begin halving strings. 

If there is something that is really prohibitive about the behavior in using the tool then that would be good to know, and then perhaps the effort invested is worth it. Let me know your thoughts.

**Comment by pixelzoom** [comment] 2023-01-24 22:55
> Right now we're stripping out the string pattern and doubling it at the end, rather than addressing the logic to remember it's original placement in the string. This logic gets especially tricky when we begin halving strings.

I can see how that would be easier (necessary?) when making strings shorter than their original length.  But it's not necessary if you're making strings longer than their initial length. For example, if the initial string pattern is `"x = {{x}}"`, it's preferrable that the doubled string would be `"x = {{x}}x = {{x}}"`, not `"x = x = {{x}}{{x}}"`.    @marlitas would that be difficult to change?

**Comment by pixelzoom** [comment] 2023-01-25 00:46
Lots of work in the above commits. Summary:

* Implemented the behavior that I suggested in https://github.com/phetsims/chipper/issues/1319#issuecomment-1402796456.  If the string is getting longer than its initial length, it is simply double. If it's getting shorter than its initial value, then pattern placeholders are moved to the end of the shortened string. See `applyToString`.

* Fixed a bug with spacebar. It was not resetting `stringFactor` to 1.

* Improved readability by factoring out keyCode constants, and factoring out function for the actions associated with keyCodes.

* Factored out private functions instead of relying on confusing closures. These functions appear after (outside) the class definition.

I went over most of this with @marlitas on Zoom, but I'll assign to her for a review.  If this looks OK to you, I'm OK with closing this issue.

**Comment by pixelzoom** [comment] 2023-01-25 02:44
One last change (I promise :)

Something that has bugged me from the get-go is the overall design of DynamicStringTest.ts.  It's a `class`, but it has no constructor, no fields, and consists of only one static `init` method that reilies on a bunch of closures to keep state.  This is an improper use of a class. 

In the above commit, I reworked DynamicStringTest to be a proper class, with fields for state, and public/private methods that operate on that state.   Here's how its use changed in SimDisplay.ts:

```diff
    if ( phet.chipper.queryParameters.stringTest === 'dynamic' ) {
-     DynamicStringTest.init();
+     const dynamicStringTest = new DynamicStringTest();
+     window.addEventListener( 'keydown', event => dynamicStringTest.handleEvent( event ) );
    }
```

**Comment by pixelzoom** [comment] 2023-01-25 04:21
One more thing :)

In https://github.com/phetsims/chipper/issues/1319#issuecomment-1345608678, I reported:
> (1) It's still very easy to get the sim to freeze / lockup.
> 
> Start any sim (e.g. Beer's Law Lab). Press the RIGHT arrow key ~10x. The sim will freeze, the browser (Chrome) will become totally non-responsize, and a "Force Quit" is required.
> 
> I'm not sure if this is a performance problem, and the sim is working hard to compute some really long strings. Or if the sim has crashed. (EDIT: I suspect the former, because the sim came back to life after waiting ~5 minutes.)
> 
> Perhaps there should be a limit on the number of times that strings can be doubled?

This is still a serious problem -- I locked up Chrome several times while working on this, and had to force quit each time.  So in the above commit, put a limit on the number of times that you can double strings, see `MAX_STRING_FACTOR = 8`.

**Comment by marlitas** [comment] 2023-01-25 18:00
@pixelzoom I looked through the commits and your comments and this all seems reasonable. I also ran through a couple of `DynamicStringTest` usages and it is working well and has definitely addressed concerns you have brought up in the past. 
I think these are great improvements, and I am ready to close this issue as completed. 

 I also updated the [dynamic string layout quickstart guide](https://github.com/phetsims/phet-info/blob/master/doc/dynamic-string-layout-quickstart.md) to include information and references to `DynamicStringTest`

**Closed by marlitas** 2023-01-25 18:00 UTC
Labels: status:ready-for-review

**Comment by pixelzoom** [comment] 2023-01-27 21:57
While working on https://github.com/phetsims/calculus-grapher/issues/193, I noticed that @veillette had used KeyboardEvent.code instead of the deprecated KeyboardEvent.keyCode.  So I made a similar change to DynamicStringTest.ts in the above commit. @marlitas FYI.
