### ISSUE TITLE
phet-admin user on Figaro doesn't have group-write flag set in umask

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/chipper#427] opened 2016-01-09 05:35 UTC
Immediately after phet-admin builds, I don't have the permission to modify built files without switching to the phet-admin user (via 'su').

It would make things much easier if the group-write permissions flag was set in the umask.

**Comment by jonathanolson** [comment] 2016-01-14 22:19
Whoops, my recommendation for an octal literal was apparently bad.

```
/data/share/phet/phet-repos/perennial/js/build-server/build-server.js:129
process.umask( 0o0002 );
               ^
SyntaxError: Unexpected token ILLEGAL
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
```

I made the fix to use parseInt instead, committed, pulled on figaro and restarted build-server.

**Comment by jbphet** [comment] 2016-01-20 21:13
I looked at the HTML file created by the build server immediately after building the Danish (_da) version of reactants-products-and-leftovers, and it had group write permissions.  I think this means that the change to the umask is working, but I'd like to double check on the next full production deployment.  Gravity Force Labs should be going out soon, so I will try to remember to check the permissions when that sim is deployed.

**Comment by jbphet** [comment] 2016-02-17 18:10
Molecule Shapes was republished recently (v1.1.2), and all the files had group write permissions.  Looks like the issue is resolved, closing.

**Closed by jbphet** 2016-02-17 18:10 UTC
