### ISSUE TITLE
Update browserify list in transpile

### ISSUE THREAD

**Issue by zepumph** [phetsims/chipper#1323] opened 2022-09-07 23:03 UTC
Currently we have:

https://browsersl.ist/#q=%3E+0.5%25%2C+safari+10-11%2C+Firefox+ESR%2C+not+IE+11%2C+ios_saf+11
> ">0.5%, safari 10-11, Firefox ESR, not IE 11, ios_saf 11"

I recommend:

https://browsersl.ist/#q=%3E+0.25%25%2C+not+dead
> ">0.25%, not dead"

It increases our coverage from 89% to 92.5% and removes some very outdated, hard coded browser versions.

We don't have to change our IE11 logic, we can still have 

`> 0.25%, not dead, not IE 11` or `> 0.25%, not dead, IE 11` depending.

@jonathanolson, can you think of any reason to keep the current browsers. For example we are hard coding safari 10 and 11, why? I'm happy to implement.

**Comment by zepumph** [comment] 2022-09-07 23:04
Discovered while debugging https://github.com/phetsims/ratio-and-proportion/issues/508 with @samreid.

**Comment by jonathanolson** [comment] 2022-09-13 01:21
> @jonathanolson, can you think of any reason to keep the current browsers. For example we are hard coding safari 10 and 11, why? I'm happy to implement.

I'm fine if this changes to something closer to our supported platforms. No particular relevant-for-now reason we have those hard-coded.

**Comment by zepumph** [comment] 2022-09-13 16:15
Great, thanks!

**Comment by samreid** [comment] 2022-10-28 20:21
This commit increases the heap size of Geometric Optic Basics Built PhET brand from 38.1MB to 58.7MB.  Startup time feels a little slower too.

**Comment by samreid** [comment] 2022-10-28 20:37
`> 0.43%, last 2 versions, Firefox ESR, not dead` report 90% and still gives us the smaller size

**Comment by samreid** [comment] 2022-10-28 20:40
According to https://browsersl.ist/#q=defaults,

> Use [defaults](https://browsersl.ist/#q=defaults) if you're building a web application for the global audience.

> You can pick a sound set of versions with the [defaults](https://browsersl.ist/#q=defaults) query which is a shortcut for > 0.5%, last 2 versions, Firefox ESR, not dead. It matches recent versions of popular and supported browsers worldwide and includes Firefox Extended Support Release which is updated roughly annually.

> The [defaults](https://browsersl.ist/#q=defaults) query was thoroughly designed by the Browserslist community. It helps promote best practices and avoid common pitfalls.

So maybe `defaults` sounds good?

**Comment by zepumph** [comment] 2022-10-28 21:34
Seems reasonable to me!

**Comment by samreid** [comment] 2022-10-28 21:43
OK pushed.  Confirmed the build size is lower.  @zepumph or @jonathanolson can you please spot check?

By the way, here is my binary search that led here:

```
10/28/22: 58.8M
4/1/22 42.4M
5/1/22 42.5M
6/1/22 46.3M
7/1/22 46.7M
8/1/22 50.3M
9/1/22 52.4M
10/1/22 82.5M
9/15/22 82.5M
9/7/22  BROKEN
9/6/22  48.8M
9/12/22  49.3M
9/14/22  84.3M
```

**Comment by jonathanolson** [comment] 2022-10-28 23:37
Looks good to me, can we confirm that this is working on all of our supported platforms?

**Comment by samreid** [comment] 2022-10-29 00:26
Perhaps an upcoming RC test will help us verify this is OK.  @KatieWoe can you please be aware of this issue for the next round of QA testing?

**Comment by pixelzoom** [comment] 2022-10-31 19:55
@KatieWoe asked:
> Ok. Can you give some details on what we should look for?

Part of this issue was memory footprint. So you want to make sure that sims are not using significantly more memory than the were on previous memory tests.    For example, see https://github.com/phetsims/scenery-phet/issues/769#issuecomment-1295233125, which is where I reported this (and is for some reason not referenced in this issue.)

I have no idea what you should look for in regards to transpiler setting, what problems might manifest and how to notice/test them, etc.  @zepumph @samreid?

I'm also not clear on how this impacts moving forward on https://github.com/phetsims/geometric-optics-basics/issues/27.

**Comment by samreid** [comment] 2022-10-31 20:11
I feel it’s unblocked and testing can happen during GO:B dev test.

**Comment by pixelzoom** [comment] 2022-10-31 20:49
@samreid and I looked at this issue on Zoom.  There's a serious problem here. None of the changes that have been made to transpile.js `browesers` result in builds that match the [system requirements on the PhET website](https://phet.colorado.edu/en/help-center/running-sims).  And for quite some time, PhET has likely been building an publishing sims that won't run on the advertised "supported platforms".    System requirements should be reviewed/revised, and then  transpile.js `browesers` should be adjusted.  

So @KatieWoe, this is most definitely not ready for testing.

This feels like high-priorty and blocks-publication to me, so let's start there.

**Comment by kathy-phet** [comment] 2022-10-31 21:45
I'm not sure I am following the scope of this issue. I'll connect with @samreid tomorrow to check in on this.

**Comment by samreid** [comment] 2022-11-01 03:06
For example, here are the discrepancies for Mac Safari versions.

| Platform | Requirements  | GAO RC 1.6 Test Matrix | Target Pre-Sept | Target Post-Sept | Target defaults | 
| ------------- | ------------- | ------------- | ------------- | ------------- | ------------- |
| Safari  | 13+  | 16  | 10,11,15.6  | 13.1+ |   15.6+ |

Our requirements say we support Safari 13+.  But before September 2022, we were not outputting code that guaranteed compatibility with that platform.  It seems the RC was tested on Safari 16 (if I'm reading that test matrix correctly).  The targets in September changed to output to 13.1 and higher (not supporting 13.0) and the version I just updated it to targets 15.6+.

It would be good to increase consistency here, keeping in mind that Safari and Mobile Safari are linked to OS versions (can only upgrade so far without upgrading the OS).

The page https://browsersl.ist/#q=%3E+0.1%25 estimate the amount of usage of platforms.  For instance, it says IE11 is at 0.48 % and Safari 13.1 is 0.26 %.

At some point, targeting more platforms increases heap size (40MB to 60MB).  Probably also increases download size (I haven't measured this) and the startup time (I haven't measured this).  May also decrease runtime performance (I haven't measured this).

**Comment by kathy-phet** [comment] 2022-11-01 12:54
This seems to match our system requirements. @samreid - does this increase the heapsize? defaults, iOS>= 13, safari>=13
Coverage =92.8%

**Comment by KatieWoe** [comment] 2022-11-01 14:37
Now that iPadOS 16 and MacOS 13 are released, we discussed dropping the oldest supported iOS and MacOS, which I believe were iOS 13 and MacOS 10.13. If we still are dropping those then Safari 14 would be the oldest supported.

**Comment by marlitas** [comment] 2022-11-01 16:24
> This seems to match our system requirements. @samreid - does this increase the heapsize? defaults, iOS>= 13, safari>=13
Coverage =92.8%

@samreid and I looked at this, and including safari>=13 does not increase our heap size. 

We used this browser configuration in transpile.js:
```js
const browsers = [
    'defaults',
    'safari >= 13'
  ];
```

**Comment by samreid** [comment] 2022-11-01 17:19
> Is there a way to make it so that we never have to adjust this again?

My hope is that "defaults" will solve that for us, if we are OK with its numbers.  So many good things said about defaults in https://github.com/phetsims/chipper/issues/1323#issuecomment-1295444767

**Comment by kathy-phet** [comment] 2022-11-01 17:38
Let's go with this to unblock for now .. 
const browsers = [
    'defaults',
    'safari >= 13',
    'iOS >= 13'
  ];
  
This matches what we say on the website.

**Comment by kathy-phet** [comment] 2022-11-01 17:39
@samreid - You can make an issue to consider supported browsers, and potentially update to supported systems. This requires making a change in our website language to match what "defaults" has. And should be communicated to our client partners as well.

**Comment by kathy-phet** [comment] 2022-11-01 17:57
@pixelzoom - With this change, (marla committed above), does it make sense to rebuild the dev tests for GOB?

**Comment by oliver-phet** [comment] 2022-11-01 18:32
> @oliver-phet - Can you add in the use we see at the PhET website for the iOS and Safari versions of browsers?

Last 30 days (3,872,563 Safari users):
*Total does not = 100% because of strange browser versions (i.e. "Safari 13609.3.5.1.5")

Safari 7+ | 320 | 0.008%
-- | -- | --
Safari 8+ | 80 | 0.002%
Safari 9+ | 900 | 0.023%
Safari 10+ | 2357 | 0.061%
Safari 11+ | 3028 | 0.079%
Safari 12+ | 57981 | 1.504%
Safari 13+ | 52747 | 1.368%
Safari 14+ | 316834 | 8.218%
Safari 15+ | 2613689 | 67.795%
Safari 16+ | 683626 | 17.732%

Total ~95% of users on Safari 13+
Total ~1.6% of users on <Safari 13.

**Comment by kathy-phet** [comment] 2022-11-01 18:58
Thanks, Oliver. @samreid - defaults don't include all versions of Safari 14 , so we should not be using just defaults imo. 

@marlitas - Your commit looks like it updated with the safari and iOS needs. 

Any reason I cannot close this issue?

**Comment by pixelzoom** [comment] 2022-11-01 19:56
> @pixelzoom - With this change, (marla committed above), does it make sense to rebuild the dev tests for GOB?

@kathy-phet your call. If you'd like to cancel the current dev test, please note in https://github.com/phetsims/qa/issues/847.

The dev version was built when transpiler.ts was configured for "default".   Because it's a dev version, there's no release branch to patch, and we'll pick up the transpiler.ts on the next dev version, or when we create the first RC.

**Comment by kathy-phet** [comment] 2022-11-02 00:00
@pixelzoom - Looks like we don't test those browsers in a dev test anyways, so no need to redo the dev. 

I'm going to close this issue. @samreid @marlitas - reopen if you see a reason.

**Comment by pixelzoom** [comment] 2022-11-10 22:12
Reopening. We had a design meeting on 11/10/2022 where some important decisions were made. 

* macOS 10.13 will be dropped from System Requirements. @KatieWoe will make an issue to update the PhET website.
* We'll leave transpile.js the way it currently is.
* We will sometime has older platforms in transpile.js that are not advertised in System Requirements on the PhET website.
* We should never remove platforms that are advertised in the System Requirements on the PhET website without a broader discussion.

**Comment by pixelzoom** [comment] 2022-11-10 22:13
Reopening. We had a design meeting on 11/10/2022 where some important decisions were made.

macOS 10.13 will be dropped from System Requirements. @KatieWoe will make an issue to update the PhET website.
We'll leave transpile.js the way it currently is.
We will sometime has older platforms in transpile.js that are not advertised in System Requirements on the PhET website.
We should never remove platforms that are advertised in the System Requirements on the PhET website without a broader discussion.
I will document these decisions in transpile.js, at the appropriate place.

**Comment by kathy-phet** [comment] 2022-11-11 17:22
@pixelzoom - I didn't think this was for Babel? I thought browserify was broader - back converting code to support use of newer js patterns.

**Comment by pixelzoom** [comment] 2022-11-11 17:27
The format for the `browsers` list is indeed broader, see the link I provided in the comment (https://babeljs.io) which states:
> Shared browser compatibility config for popular JavaScript tools like Autoprefixer, Babel, ESLint, PostCSS, and Webpack

transpiler.js is more specific. It passes the `browsers` list to babel.  Line 39:

```typescript
 return babel.transform( jsInput, {
...
      targets: {
        browsers: browsers
      }
```

**Comment by pixelzoom** [comment] 2022-11-11 17:30
Also note the documentation of transpiler.js at line 4:

```js
  * Handles transpilation of code using Babel
```

So I'm going to close this. Reopen if you have more questions.

**Closed by pixelzoom** 2022-11-11 17:30 UTC
Labels: priority:2-high

**Comment by samreid** [comment] 2022-11-11 18:14
Babel is a 3rd party open source library which transpiles code versions, not to be confused with phetsims/babel which contains our sim translations.
