### ISSUE TITLE
Continuous Testing: Warning: ENOENT: no such file or directory, scandir '../phet-io-wrappers/node_modules'

### ISSUE THREAD

**Issue by zepumph** [phetsims/chipper#569] opened 2017-04-25 00:03 UTC
This problem came up when I merged 'exileWrappers' into master. It wasn't a problem locally, and I can't seem to reproduce it, but all phet-io builds are failing on the continuous testing with this error:
`Warning: ENOENT: no such file or directory, scandir '../phet-io-wrappers/node_modules'`

I will investigate further in the morning.

**Comment by Denz1994** [comment] 2017-04-25 00:07
I am not getting this error. But I haven't pulled from master since around 8:20 am this morning.

**Comment by jonathanolson** [comment] 2017-04-25 03:35
Testing on aqua, it looks like this issue is caused by my use of symbolically linking node_modules directories as a time-saving measure. I'll run a few extra tests to see if I can get "npm update" to run massively concurrently.

**Comment by jonathanolson** [comment] 2017-04-25 04:00
Two runs of 'npm update' (on freshly-checked-out active-runnables) ran between 7-7.5min so far, so I'll check parallel invocations (with different cache directories).

**Comment by jonathanolson** [comment] 2017-04-25 04:16
The following script approximation is running in ~54 seconds:
```sh

mkdir caches
PIDARRAY=()
for sim in `cat chipper/data/active-runnables | xargs`
do
  mkdir caches/${sim}
  echo ${sim}
  cd ${sim}
  npm update --cache=../caches/${sim} &
  PIDARRAY+=($!)
  cd ..
done

for pid in "${PIDARRAY[@]}"
do
  wait ${pid}
done
```

I'll do some testing to make sure it's sufficient.

**Comment by jonathanolson** [comment] 2017-04-25 05:22
Modifications to use parallel npm updates (with the --cache parameter as seen above) has been moved to aqua on bayes. I'll check back in soon to see if it fixes the issue.

**Comment by jonathanolson** [comment] 2017-04-25 05:33
Looks like this was successful in resolving the issues, closing.

**Closed by jonathanolson** 2017-04-25 05:33 UTC
Labels: priority:2-high

**Comment by zepumph** [comment] 2017-04-25 14:45
Thanks @Denz1994 and @jonathanolson for figuring this out, I appreciate it.
