### ISSUE TITLE
Get rid of version.js

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#74] opened 2014-11-18 17:51 UTC
We should make it so that the package.json version is the only place the version is located, and becomes accessible to the JS code at runtime.

**Comment by pixelzoom** [comment] 2015-02-24 17:26
Related to https://github.com/phetsims/chipper/issues/4

**Comment by pixelzoom** [comment] 2015-04-30 18:58
Duplicate of #4, @jonathanolson is working on this.

**Closed by pixelzoom** 2015-04-30 18:58 UTC
