### ISSUE TITLE
Investigate live reloading / hot module replacement / webpack-dev-server

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/chipper#864] opened 2020-02-06 19:32 UTC
For es6 modules, it would be good to see if webpack-dev-server can create faster iteration times.

> (SR, JO, ??, low overhead during sim dev, 2 hours?) [Sprintable, post-publication.  But good to do early on while concrete is wet.] Experiment with live reloading and hot module replacement.  To optimize iteration time.  See https://github.com/phetsims/chipper/issues/845
JO: Unclear whether single entry point vs multiple vs all (sims) would be best

**Comment by chrisklus** [comment] 2020-02-26 19:46
- [ ] start off by looking at webpack.config.js and then delete that file

**Comment by chrisklus** [comment] 2020-02-26 20:01
Duplicate of https://github.com/phetsims/chipper/issues/845, migrating content and closing.

**Closed by chrisklus** 2020-02-26 20:01 UTC
Labels: chipper:es6-modules
