### ISSUE TITLE
How to cacheBust preloads

### ISSUE THREAD

**Issue by zepumph** [phetsims/chipper#755] opened 2019-05-09 21:47 UTC
From https://github.com/phetsims/axon/issues/243, we found that all the phet-io api preloads were cached and need dev tools to be opened to clear the cache. This occurs more here I think than others because these preloads are constantly changing, and that is likely to not change in the near future. Is there a way to easily cacheBust these preloads?

We should at least give this a PSA at a dev meeting, and perhaps we can brainstorm to see if anyone has ideas about how to implement a preload cachebusting strategy (probably in the devleopment html file).  

One simple strategy could be `script.src = preloadURL+ 'cacheBust=${Date.now()'};`

The key here is to get this cache busting to be respected by the query parameter we have in init-globals, which we could, just separately, without QSM.

Currently we may not be able to iterate on a device like an iPad since we can't clear the cache easily.

**Comment by zepumph** [comment] 2019-05-09 21:50
Oh! The main spot this has become incredibly annoying in is aqua fuzz tests. There is a sort of catch 22 when trying to run all sims because if you open your dev tools, you reload the elements files (and thus avoid a phet-io api assertion), but then I will manually pause in a debugger if there is ever an uncaught error, so it is difficult to test all sims while iterating on the preloads.

**Comment by pixelzoom** [comment] 2019-05-16 19:14
5/16/19 dev meeting:

* @samreid we should handle cache busting uniformly in all code. Currently we're inconsistent.
* @samreid has to turn off cache busting when setting breakpoints in dev tools.

- [ ] We will add cache busting for preloads.  
- [ ] Rename `cacheBuster` query parameter to `cacheBust`, change type to 'flag' (off by default).
- [ ] aqua tests in phetmarks will add `?cacheBust` since they are intended to be run with dev tools closed.

@zepumph volunteered to do this.

**Comment by zepumph** [comment] 2019-07-12 02:50
All 4 steps have been dealt with. In this issue, I updated `CHIPPER/sim-development.html` and phetmarks. Everything else is just running grunt update. It's about the same for the other issues. @pixelzoom please review

**Comment by zepumph** [comment] 2019-07-12 18:56
To be clear, as part of this review, please hit https://github.com/phetsims/chipper/issues/759 and https://github.com/phetsims/chipper/issues/767 as well.

**Comment by pixelzoom** [comment] 2019-07-13 17:15
While I did take [notes in 5/16/19 dev meeting](https://github.com/phetsims/chipper/issues/755#issuecomment-493196614), I don't feel like I'm familiar enough with how PhET is using cache busting to give this a proper review. @zepumph could you please assign someone else?

**Comment by zepumph** [comment] 2019-07-13 18:05
@samreid can you take this on? If not please assign to @ariel-phet to assign a reviewer.

**Comment by samreid** [comment] 2019-07-15 02:54
I'm happy to be the assignee, but will likely not get to this for at least a month at current priority.  @ariel-phet feel free to assign someone else or change the priority if it needs to be done sooner.

**Comment by samreid** [comment] 2019-08-15 04:56
During my review, I confirmed the following desirable changes:

* When specifying ?cacheBust, the preloads and requirejs modules get a ?bust=N parameter
* When not specifying ?cacheBust, neither the preloads nor requirejs modules get ?bust=N
* All of the aqua tests correctly have ?cacheBust in the URL

I noticed that the requirejs regex can have false positives.  For instance, the regex `/(^|\?|&)cacheBust/.test( location.search )` returns true for the string ?cacheBust=false.  Hopefully this is not a problem if everyone is on board using the flag (instead of boolean) syntax.  @zepumph what do you think about this part?

Another thing I noticed, probably unrelated to the changes committed for this issue, is that requirejs modules show a `?` in the chrome mouseover popup for the filename.  This happened even when I completely removed `urlArgs` from the config file.  @zepumph it would be great for you to take a look and comment on this part before we move away from this issue (though it may be out of our control).

![image](https://user-images.githubusercontent.com/679486/63073436-0361b000-bee6-11e9-8c7a-63c1b8216cb2.png)

I also considered that string template literals are not supported on IE11, but I believe we already made the decision that sims cannot run in requirejs mode on IE11 anyways.

**Comment by samreid** [comment] 2019-08-15 16:02
Two more thoughts:

* Every now and then someone reports a problem on phettest.colorado.edu which amounts to stale files.  Should we default phettest.colorado.edu links to use `?cacheBust`?
* The documentation at https://requirejs.org/docs/api.html says 

> During development it can be useful to use [cache busting], however be sure to remove it before deploying your code.

@zepumph what do you think about the former, and why do you think there is such a note about the latter?

**Comment by zepumph** [comment] 2019-08-23 01:13
>Since ?cacheBust=false is caught downstream by Query String Machine, this is probably not a problem.

Agreed and sounds good.

>@zepumph it would be great for you to take a look and comment on this part before we move away from this issue (though it may be out of our control).

I completely removed urlArgs from friction's config. I then had to go through usages of `config.urlArgs` in a few plugins and removed those usages. Then I looked at the network tab and didn't see the `?`.

![image](https://user-images.githubusercontent.com/6856943/63559859-269ce880-c500-11e9-9655-6ee3b5a9a866.png)


>Every now and then someone reports a problem on phettest.colorado.edu which amounts to stale files. Should we default phettest.colorado.edu links to use ?cacheBust?

That is a great idea! All that needs to be done now is to make sure that the index.html page is pulled on phettest. I'm not sure how that works. But if you go through phetmarks now, it auto cache busts.

>and why do you think there is such a note about the latter?

I don't think this applies to us, because we are using the requirejs optimizer to build. See `requireBuild`. There are no usages of `cache` there. Furthermore, there are no usages of `cache` in https://github.com/requirejs/r.js/blob/master/build/example.build.js (liked to from that file). 



@KatieWoe do you know how to pull changes onto phettest? It is likely just a copy of phettest on the computer that is being hosted that needs to be pulled. Any thoughts?

**Comment by KatieWoe** [comment] 2019-08-23 14:39
Not sure.  I refreshed perennial, but don't think that's really enough.  Should we discuss it on Slack?

**Comment by zepumph** [comment] 2019-08-23 16:42
@zepumph and @chrisklus were able to log into phettest, and copy the new and updated `index.html` page from `phetmarks/phettest/index.html` into the spot it lives on phettest (at the root with all other phet repos: `~/phet/index.html`). @KatieWoe we should now have cache busting on the phettest links, as well as, by default, links from phetmarks when on phettest.  @samreid anything else for this issue?

**Comment by samreid** [comment] 2019-08-24 03:58
I tested phettest and it correctly appends `?cacheBust`, thanks!  I can't think of anything else for this issue, closing.

**Closed by samreid** 2019-08-24 03:58 UTC
Labels: status:ready-for-review, type:misc
