### ISSUE TITLE
CT: full api expected

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#1032] opened 2021-04-06 16:14 UTC
This is happening for ph-scale and projectile-motion. Unclear whether other sims are affected.

```
projectile-motion : build
Build failed with status code 1:
Running "report-media" task

Running "clean" task

Running "build" task
Building runnable repository (projectile-motion, brands: phet, phet-io)
Building brand: phet
>> Webpack build complete: 4468ms
>> Production minification complete: 28984ms (2114185 bytes)
>> Debug minification complete: 1ms (6384119 bytes)
Building brand: phet-io
>> Webpack build complete: 3331ms
>> Production minification complete: 23298ms (2134931 bytes)
>> Debug minification complete: 22965ms (2408093 bytes)
>> No client guides found at ../phet-io-client-guides/projectile-motion/, no guides being built.
Fatal error: Perennial task failed:
AssertionError [ERR_ASSERTION] [ERR_ASSERTION]: full api expected
at module.exports (/data/share/phet/continuous-testing/ct-snapshots/1617722176576/chipper/js/grunt/copySupplementalPhetioFiles.js:294:5)
at module.exports (/data/share/phet/continuous-testing/ct-snapshots/1617722176576/chipper/js/grunt/buildRunnable.js:355:5)
at /data/share/phet/continuous-testing/ct-snapshots/1617722176576/chipper/js/grunt/Gruntfile.js:255:11
at wrap (/data/share/phet/continuous-testing/ct-snapshots/1617722176576/chipper/js/grunt/Gruntfile.js:74:7)

Full Error details:
AssertionError [ERR_ASSERTION]: full api expected

Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db
Error [Error: Navigation failed because browser has disconnected!
at /data/share/phet/continuous-testing/ct-snapshots/1617722176576/chipper/node_modules/puppeteer/lib/cjs/puppeteer/common/LifecycleWatcher.js:51:147
at /data/share/phet/continuous-testing/ct-snapshots/1617722176576/chipper/node_modules/puppeteer/lib/cjs/vendor/mitt/src/index.js:51:62
at Array.map (<anonymous>:null:null)
at Object.emit (/data/share/phet/continuous-testing/ct-snapshots/1617722176576/chipper/node_modules/puppeteer/lib/cjs/vendor/mitt/src/index.js:51:43)
at CDPSession.emit (/data/share/phet/continuous-testing/ct-snapshots/1617722176576/chipper/node_modules/puppeteer/lib/cjs/puppeteer/common/EventEmitter.js:72:22)
at CDPSession._onClosed (/data/share/phet/continuous-testing/ct-snapshots/1617722176576/chipper/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:247:14)
at Connection._onClose (/data/share/phet/continuous-testing/ct-snapshots/1617722176576/chipper/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:128:21)
at WebSocket.<anonymous> (/data/share/phet/continuous-testing/ct-snapshots/1617722176576/chipper/node_modules/puppeteer/lib/cjs/puppeteer/node/NodeWebSocketTransport.js:17:30)
at WebSocket.onClose (/data/share/phet/continuous-testing/ct-snapshots/1617722176576/chipper/node_modules/puppeteer/node_modules/ws/lib/event-target.js:136:16)
at WebSocket.emit (events.js:315:20)
at WebSocket.emitClose (/data/share/phet/continuous-testing/ct-snapshots/1617722176576/chipper/node_modules/puppeteer/node_modules/ws/lib/websocket.js:198:10)
at Socket.socketOnClose (/data/share/phet/continuous-testing/ct-snapshots/1617722176576/chipper/node_modules/puppeteer/node_modules/ws/lib/websocket.js:886:15)
at Socket.emit (events.js:315:20)
at TCP.<anonymous> (net.js:673:12)
]
Snapshot from 4/6/2021, 9:16:16 AM
```

**Comment by samreid** [comment] 2021-04-06 16:46
May be related to https://github.com/phetsims/chipper/issues/1022

**Comment by zepumph** [comment] 2021-04-21 21:05
> Improve the error message.


Done in https://github.com/phetsims/chipper/commit/31729b606c7099e3b7bd33f8a1160bd273068fc8

**Comment by zepumph** [comment] 2021-04-28 21:58
I can't even build phet-io-test-sim right now. The good news is that. . . this means I have a reproduceable case!

It works fine from `grunt generate-phet-io-api`, but not from build. Looks like the only difference is the `fromBuiltVersion` option.

I am able to toggle that to true in the grunt task and reproduce the problem when it loads a stale copy of the built sim. I wonder what the minified phet-io sim has that the unbuilt one doesn't.

**Comment by samreid** [comment] 2021-04-28 22:09
A great discovery!

**Comment by zepumph** [comment] 2021-04-28 22:30
Now that I understand the problem better, I'm realizing that the puppeteer callbacks in generatePhetioMacroAPI are a total mess. There are many possible code paths that will yield in this promise being rejected multiple times, or possible also rejected and resolved:

```js



```




Side note, I wonder if this only happens in built mode because the larger file size times out something in node while it loads? Probably not because why would that be so inconsistent.

**Comment by zepumph** [comment] 2021-04-28 22:46
The error is spawning from page.goto, perhaps https://github.com/puppeteer/puppeteer/issues/4275 will help.

**Comment by zepumph** [comment] 2021-04-28 23:05
When I updated to puppeteer v9, I no longer get these navigation errors. In addition to making sure we can't double reject, I think we should do that over in https://github.com/phetsims/chipper/issues/1041

**Comment by zepumph** [comment] 2021-04-29 00:13
It seems the primary error was two fold:

1. when you call `await page.close()`, which we did right before we resolved with the API, it triggers a `pageerror` which we are catching and using to reject.
2. Not positive about this one, but I think the `try` around `page.goto()` was catching errors coming from the sim, that were also handled by the page.on callbacks.

The solution is the above commit. I am not positive that it is totally solved, but I KNOW it is better than what was in master. All day (perhaps 30 times), I failed to build a phet-io sim because it rejected with an error: `Navigation failed because browser has disconnected!` before it could resolve. I now realize that it actually had the API, and this error was caused by pre-maturely cleaning up and not handling the clean up case.


@samreid, I'm unsure that I have solved this in the best way, with two flags making sure we don't resolve/reject/page.close() more than once. Please recommend other options if they come to you. Please review the commit.


I will also note that https://github.com/phetsims/chipper/issues/1041 was a red herring, and not needed afterall for this issue. I could reproduce this problem on v9 as well, it was just a bit differently worded. I will close that issue.

**Comment by zepumph** [comment] 2021-04-29 00:14
I have now made >10 builds without encountering this issue. Wahoo!

**Comment by zepumph** [comment] 2021-04-30 21:31
I have not encountered the error since these changes. With perhaps another 10 builds or so.

**Comment by jonathanolson** [comment] 2021-05-09 02:20
Had a failure with a maintenance release build, is this related? Does that mean I'll need to maintenance release sims without the fix?

```
Error: Failure updating dependencies for build-an-atom to 1.7: Error: grunt.cmd --brands=phet,phet-io --locales=en --allHTML --debugHTML in ../build-an-atom failed with exit code 1 and stdout:
Running "lint-all" task

Running "report-media" task

Running "clean" task

Running "build" task
Building runnable repository (build-an-atom, brands: phet, phet-io)
Building brand: phet
>> Webpack build complete: 2926ms
>> Production minification complete: 16561ms (1729585 bytes)
>> Debug minification complete: 0ms (5987600 bytes)
Building brand: phet-io
>> Webpack build complete: 2194ms
>> Production minification complete: 13984ms (1744930 bytes)
>> Debug minification complete: 13719ms (1997963 bytes)
>> No client guides found at ../phet-io-client-guides/build-an-atom/, no guides being built.
Fatal error: Perennial task failed:
Error: Navigation failed because browser has disconnected!
  at C:\Users\olson\phet\git\chipper\node_modules\puppeteer\lib\cjs\puppeteer\common\LifecycleWatcher.js:51:147
  at C:\Users\olson\phet\git\chipper\node_modules\puppeteer\lib\cjs\vendor\mitt\src\index.js:51:62
  at Array.map (<anonymous>:null:null)
  at Object.emit (C:\Users\olson\phet\git\chipper\node_modules\puppeteer\lib\cjs\vendor\mitt\src\index.js:51:43)
  at CDPSession.emit (C:\Users\olson\phet\git\chipper\node_modules\puppeteer\lib\cjs\puppeteer\common\EventEmitter.js:72:22)
  at CDPSession._onClosed (C:\Users\olson\phet\git\chipper\node_modules\puppeteer\lib\cjs\puppeteer\common\Connection.js:247:14)
  at Connection._onMessage (C:\Users\olson\phet\git\chipper\node_modules\puppeteer\lib\cjs\puppeteer\common\Connection.js:94:25)
  at WebSocket.<anonymous> (C:\Users\olson\phet\git\chipper\node_modules\puppeteer\lib\cjs\puppeteer\node\NodeWebSocketTransport.js:13:32)
  at WebSocket.onMessage (C:\Users\olson\phet\git\chipper\node_modules\ws\lib\event-target.js:132:16)
  at WebSocket.emit (events.js:315:20)
  at Receiver.receiverOnMessage (C:\Users\olson\phet\git\chipper\node_modules\ws\lib\websocket.js:835:20)
  at Receiver.emit (events.js:315:20)
  at Receiver.dataMessage (C:\Users\olson\phet\git\chipper\node_modules\ws\lib\receiver.js:437:14)
  at Receiver.getData (C:\Users\olson\phet\git\chipper\node_modules\ws\lib\receiver.js:367:17)
  at Receiver.startLoop (C:\Users\olson\phet\git\chipper\node_modules\ws\lib\receiver.js:143:22)
  at Receiver._write (C:\Users\olson\phet\git\chipper\node_modules\ws\lib\receiver.js:78:10)
  at writeOrBuffer (_stream_writable.js:352:12)
  at Receiver.Writable.write (_stream_writable.js:303:10)
  at Socket.socketOnData (C:\Users\olson\phet\git\chipper\node_modules\ws\lib\websocket.js:910:35)
  at Socket.emit (events.js:315:20)
  at addChunk (_stream_readable.js:302:12)
  at readableAddChunk (_stream_readable.js:278:9)
  at Socket.Readable.push (_stream_readable.js:217:10)
  at TCP.onStreamRead (internal/stream_base_commons.js:186:23)

```

**Comment by jonathanolson** [comment] 2021-05-10 16:36
I'm getting this also in molecule-polarity 1.1, going to plan to patch this up first before other things.

**Comment by jonathanolson** [comment] 2021-05-10 16:51
I'm looking to see where the potential race condition was added. It looks like the file's moved a bit, for reference it's had these names/locations (which might need to be maintenanced):

- chipper/js/phet-io/generatePhetioMacroAPI.js
- chipper/js/phet-io/generateMacroAPI.js
- chipper/js/phet-io/generatePhetioAPI.js
- chipper/js/grunt/phet-io/generatePhetioAPI.js
- chipper/js/grunt/phet-io/generatePhetioAPIFiles.js
- chipper/js/grunt/phet-io/generatePhetioFiles.js

**Comment by zepumph** [comment] 2021-05-11 21:55
In https://github.com/phetsims/chipper/commit/c30502c26d3a6f30c9fe7dbcdfad9ae2ecf9edfc @jonathanolson and I did a co-review of the above commit. After the MR we are doing currently, I think this is ready to close.

**Comment by samreid** [comment] 2021-05-11 21:56
Thanks!

**Comment by jonathanolson** [comment] 2021-05-12 00:18
Should be patched up, unassigning until QA verification.

**Comment by liam-mulhall** [comment] 2021-05-18 20:14
From Slack:

> I think you can just close chipper#1032.  It was a failure due to puppeteer (used by CT) failing, not something wrong with the PhET-iO API.

Closing.

**Closed by liam-mulhall** 2021-05-18 20:14 UTC
Labels: dev:maintenance-release, dev:phet-io, status:ready-for-review, type:automated-testing, type:bug
