### ISSUE TITLE
how to support changes to common code in RC process?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#395] opened 2015-10-29 19:32 UTC
Lessons learned from S2015R, and thoughts on how to modify PhET’s SCM process to support maintenance/fixes to common code.

Notes from 10/29/15 dev meeting:

SR: CM said: “This will require a change to common code, so the next RC will need to use master of all repos.”  In my opinion, this is one of the problems we should try to surmount.  Most of the changes we want to make to a simulation are due to common code changes.
JO: we need more automated testing, playback
AP: For next developer meeting, everyone have a proposal for how to support changes to common code in the RC process.

**Comment by samreid** [comment] 2015-11-02 18:23
There are several related problems here.  I'll restrict my proposals to the specific problem instance, which seems most prevalent at the moment:
(a) Given a single published sim, with given shas and a required minimal change in one of the common dependencies, how to create the new version of the simulation?

Note: this does not address the related problems:
(b) how to deploy a small common code change to *many* simulations
(c) how to deploy larger/major/complex changes to common code library to a single sim

Proposal 1 "branch-common-code": for the common library that needs to be modified, create a branch based on the sha named '$simulation-$version-$fix` where fix is a nickname for the bug being fixed.  Make the fix in the branch, perform minor testing and redeploy.

Proposal 2 "versioned built files": when a simulation is published, commit a single file (but not uglified or minified) HTML into version control for that version, let us call it $sim_build.html (contains all dependencies).  When changes need to be made, the $sim_build.html file can be directly edited, committed, uglified, minified and republished.

Proposal 3 "versioned libraries": move towards versioned libraries.  axon-1.0.1, scenery-0.2.1, etc.  When publishing a simulation, use the latest stable published version of each library.  Republishing with a minor change to a single common repository means rebuilding a common library (possibly from a branch) and using that.

Proposal 4 "augmented testing": continue developing in master and publishing from master, but spend time developing more automated testing facilities so that we can decrease the burden on RC testing.  No need to branch here, just publish a new version from master.

I'm not too familiar with how the automated build process works for translations, or how the above proposals would have to be modified to work with that.

**Comment by jbphet** [comment] 2015-11-03 21:09
It seems to me like we are running into issues right now because we have two competing goals:

1.  Publish sims with relatively new code that allows them to be translated
1.  Continue making progress of new features (phet-io and accessibility) that require significant modifications to common code

This is a new situation for us, since until recently we've been focused primarily on producing sims.  In my opinion, versioned releases of the common code is the best way to support this.  We discussed doing this back when we were establishing the initial HTML5 development process, but rejected it because it didn't seem necessary at the time.  Perhaps now it is - at least until the initial development of the major new features is completed.

Versioned releases of common/library code is also a very common practice in the software development industry, which means that Git has a number of features to help with such things.

In thinking about this, I'm envisioning a process where we decide that a release of common code is needed, and make some level of effort to ensure that master is stable.  At that point we tag master for all common code, then build versions of several simulations that are known to exercise much of the common code.  These are then tested, partially through automation and partially by the QA team.  If issues are found, a branch is made of the common code repo(s) with the issue and the fix is rolled in, and the test process is (perhaps partially) redone.  The versioning scheme would be similar to what we use now for sim releases.  The diagram below illustrates.

![common code release process sketch 2](https://cloud.githubusercontent.com/assets/3082831/10921717/67f45330-8234-11e5-9873-a2ebd8c67cf4.png)

**Comment by samreid** [comment] 2015-11-03 22:45
@jbphet to clarify your proposal... It sounds like you are saying (a) We bundle all common code into a single library, including scenery, vegas, vibe, nitro, etc... and give that a version number and branch name across all repos.  You are not saying (b) each common repo is versioned independently, such as scenery-0.2.1 and vibe-1.0.1, etc.  Did I understand that correctly?

**Comment by pixelzoom** [comment] 2015-11-05 19:36
Dev meeting notes:

Summary of current proposal:  For RC testing and maintenance, branch a common-code repository from a sha as needed. The branch name would correspond to the sim repo name and it's release branch name.  For example, if I need to patch scenery for Beer's Law Lab 1.3, then I would locate the sha for scenery in dependencies.json in the 1.3 branch of beers-law-lab. From that sha, I would then create branch "beers-law-lab-1.3" for scenery, and patch as needed.

For future milestones where we need to release all sims, we should publish dev versions of a representation sample of sims that exercises common code. After testing/fixing any common-code problems, we would tag the repositories for the milestone, and use those shas to publish all sims.

Discuss again at next dev meeting with @jonathanolson is present.

**Comment by pixelzoom** [comment] 2015-11-05 21:37
To branch from a sha:

`git branch <branchName> <sha>`

According to various Google sources (unconfirmed) the sha must be a full sha, not an abbreviated sha. That shouldn't be a problem since we're storing full shas in dependencies.json.

**Comment by samreid** [comment] 2015-11-10 18:50
@jonathanolson: in the long term, we should have an approach where we can easily redeploy all of our simulations with a common code fix.

**Comment by samreid** [comment] 2015-11-10 18:56
Consensus: we should revisit this (a) when we are releasing more maintenance releases or (b) when we want to push changes to all sims at once.

**Comment by pixelzoom** [comment] 2015-11-16 02:12
Re the consensus in https://github.com/phetsims/chipper/issues/395#issuecomment-155530969 ... I don't agree that we should wait. We have an urgent need *NOW* to solve this problem. Example: We're in RC test for ph-scale and we found a problem with scenery canvas. https://github.com/phetsims/ph-scale/issues/64 required a *1-line* fix in scenery that would be trivial to patch into ph-scale 1.2, and then we'd be good to publish.  But since we have no way to apply patches to common-code, we are forced to update to master (pulling in other changes, and potentially new problems) and do another full RC test cycle. This keeps happening over and over.  And waiting (as suggested in the consensus) will not solve the problem.

**Comment by samreid** [comment] 2015-11-16 02:46
I may have misunderstood, but I thought the plan was to use the strategy described in https://github.com/phetsims/chipper/issues/395#issuecomment-154167431 (aka branching common code repos) and then to revisit this (a) when we are releasing more maintenance releases or (b) when we want to push changes to all sims at once.  Please feel free to branch common code repos for maintenance releases.

**Comment by pixelzoom** [comment] 2015-11-16 02:49
That wasn't my understanding. After discussing on 11/12/15, I believe we decided *not* to branch off of shas, since @jonathanolson voiced concerns about that approach.

**Comment by pixelzoom** [comment] 2015-11-16 02:50
That wasn't my understanding. After discussing on 11/12/15, I thought we decided *not* to branch off of shas, since @jonathanolson voiced concerns about that approach.  And that we'd revisit this issue and try to come up with an acceptable approach at a later date.  And in the meantime, we'd continue to update to master whenever a common-code fix was needed.

**Comment by samreid** [comment] 2015-11-16 02:53
I may have been mistaken, let's wait for @jonathanolson to clarify.

**Comment by jonathanolson** [comment] 2015-11-16 06:01
It was also my understanding that https://github.com/phetsims/chipper/issues/395#issuecomment-154167431 was the decision, and that we would branch common repos as necessary, at least until we have a better solution.

I have concerns about the approach, but we don't currently have the necessary automated testing and infrastructure to handle the other approaches I was discussing.

**Comment by pixelzoom** [comment] 2015-11-16 06:09
OK, mea culpa, thanks for clarify.  Expect to see branch "ph-scale-1.2" created for scenery shortly.

**Comment by pixelzoom** [comment] 2016-01-22 19:28
Branching and patching shas has been working nicely in my experience.  I'm inclined to close this issue, and will do so unless anyone objects before Monday, 1/25/16 @ 5:00pm.

**Comment by pixelzoom** [comment] 2016-01-22 20:25
On second thought... I'll just label with 'developer-meeting'.

**Comment by samreid** [comment] 2016-01-26 05:33
I'm ok to close this issue.

**Comment by jonathanolson** [comment] 2016-01-28 17:31
I can identify 3+ fixes that could be pushed out, but haven't been due to the cost of applying them to all sims. Seems the problem is still present?

Vote to keep open, but not necessarily to re-discuss.

**Comment by samreid** [comment] 2016-01-28 17:44
> I can identify 3+ fixes that could be pushed out, but haven't been due to the cost of applying them to all sims.

I forgot about this issue and am reversing my position.

**Comment by pixelzoom** [comment] 2016-01-28 17:56
OK, let's keep it open but not discuss (so removing developer-meeting label).

**Comment by samreid** [comment] 2016-02-08 16:17
One idea occurred to me during the discussion of https://github.com/phetsims/yotta/issues/17, if we anticipate certain kinds of changes for future sims, we can try to get multiple sims to use the same branch of code.  For the sake of discussion, let's assume that we know we would need to change the analytics ID every 6 months, hence requiring a redeploy every 6 months.  In this extreme case, we could factor out the code with the analytics ID into a separate repo, create a branch and make sure every simulation is published using that branch.  Then the next time we need to update the ID, we make the change in the branch, and we can safely run a batch redeploy pointing every sim to that branch.

This is an exaggerated simplified case for purposes of discussion, which may not work in practice.  The questions are:
* Would this work with repos at the same scale of our repos, or would we need finer granularity?
* How would we get to the point where every simulation is published using the same SHAs/branches of repos that we want to be able to batch redeploy?
* Would this ever work for a large and continuously changing repo like Scenery?

**Comment by samreid** [comment] 2023-03-24 14:04
We now have a well-established maintenance release process for deploying common code changes to RCs and published sims. Closing.

**Closed by samreid** 2023-03-24 14:04 UTC
