### ISSUE TITLE
Put all locale code into one script instead of 3 scripts.

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#41] opened 2013-10-14 22:16 UTC
Currently the locale generation code is being put into 3 generated script tags like so:

```html
<script type="text/javascript">window.phetStrings={"ENERGY_SKATE_PARK_BASICS/controls.mass":"Mass","ENERGY_SKATE_PARK_BASICS/small":"Small","ENERGY_SKATE_PARK_BASICS/large":"Large","ENERGY_SKATE_PARK_BASICS/controls.friction.title":"Friction","ENERGY_SKATE_PARK_BASICS/controls.gravity.none":"None","ENERGY_SKATE_PARK_BASICS/controls.gravity.lots":"Lots"}</script>
<script type="text/javascript">window.phetLocale='en';</script>
<script type="text/javascript">
  window.phetStrings.get = function( key ) {

    //Support translation by query parameter to enable translation in the browser
    return window.phetcommon.getQueryParameter( key ) || window.phetStrings[key];
  };
</script>
```

@jonathanolson suggested to coalesce them.

**Comment by samreid** [comment] 2015-03-23 01:32
No plans to work on this at the moment, unassigning.

**Comment by pixelzoom** [comment] 2015-05-08 19:30
Where does the code in question live?

**Comment by pixelzoom** [comment] 2015-05-21 19:08
@samreid Can you point me to where this code is?

**Comment by jonathanolson** [comment] 2015-05-22 01:32
Looks like this is just from the sim template. We could save a few bytes by moving adjacent scripts into just one script tag. I don't have a strong preference for whether this should be done or not (note I think it's only 2 scripts now).

**Comment by samreid** [comment] 2015-05-22 12:49
The sim template chipper/templates/sim.html is currently:

```html
<!DOCTYPE HTML>
<html>
<head>
  <meta charset="utf-8"/>
  <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
  <meta name="viewport" content="initial-scale=1,user-scalable=no,maximum-scale=1"/>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="phet-sim-level" content="production">
  <title>SIM_TITLE</title>
<!--
HTML_HEADER
-->
</head>
<body bgcolor="black">
<img id="splash" style="position: absolute;top: 50%;left: 50%;margin-top: -210px;margin-left: -252px;" src="SPLASH_SCREEN_DATA_URI">
<script type="text/javascript">PHET_STRINGS</script>
<script type="text/javascript">PHET_INFO</script>
<script type="text/javascript">
  window.phetStrings.get = function( key ) {

    //Support translation by query parameter to enable translation in the browser
    return window.phetcommon.getQueryParameter( key ) || window.phetStrings[key];
  };
</script>
<script type="text/javascript">PRELOAD_INLINE_JAVASCRIPT</script>
<script type="text/javascript">MAIN_INLINE_JAVASCRIPT</script>
</body>
</html>
```

Would something like this work?  (I have joined all the content from the various script tags).

```html
<!DOCTYPE HTML>
<html>
<head>
  <meta charset="utf-8"/>
  <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
  <meta name="viewport" content="initial-scale=1,user-scalable=no,maximum-scale=1"/>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="phet-sim-level" content="production">
  <title>SIM_TITLE</title>
<!--
HTML_HEADER
-->
</head>
<body bgcolor="black">
<img id="splash" style="position: absolute;top: 50%;left: 50%;margin-top: -210px;margin-left: -252px;" src="SPLASH_SCREEN_DATA_URI">
<script type="text/javascript">
  PHET_STRINGS
  PHET_INFO
  window.phetStrings.get = function( key ) {

    //Support translation by query parameter to enable translation in the browser
    return window.phetcommon.getQueryParameter( key ) || window.phetStrings[key];
  };
  PRELOAD_INLINE_JAVASCRIPT
  MAIN_INLINE_JAVASCRIPT
</script>
</body>
</html>
```

We would obviously need to test this.  We should also make sure that each entry has its own semicolons, just in case.

Also, should this block start with a 'use strict'?

**Comment by jonathanolson** [comment] 2015-05-22 13:47
Can you outline the advantages? My intuition is that it would need to finish downloading the entire file before starting JS execution, whereas if it is split into multiple script tags, it can start executing earlier (and thus faster load), however that may be inaccurate.

We should at least make sure this change wouldn't cause a regression in startup time,

**Comment by samreid** [comment] 2015-05-27 00:05
I am not sure of the tradeoffs, indeed the final sentence in the issue description is:

> @jonathanolson suggested to coalesce them.

I suspect that any overhead incurred by having separate `<script>` tags would be minimal, and that running the preload code ASAP could save a little time, if that is actually happening.

I suspect that tweaks we make here won't make much difference in terms of startup time *or* readability.  However, it should be straightforward to set up a test (by creating large `<script>` chunks) to see if scripts can start executing earlier.

**Comment by jonathanolson** [comment] 2015-05-28 01:11
Also to note for testing, it's worth artificially restricting bandwidth for the test, and we would probably want to test multiple browsers.

**Comment by pixelzoom** [comment] 2016-01-22 19:38
This issue is ancient.  And I suspect that if it were still relevant, then we should have dealt with it as part of S2015R.  @samreid and @jonathanolson should this be closed?

**Comment by samreid** [comment] 2016-01-23 03:22
I haven't noted any significant problems with the current implementation, but it is up to @jonathanolson.

**Comment by jonathanolson** [comment] 2016-01-23 03:41
Seems good enough, not worried. Closing.

**Closed by jonathanolson** 2016-01-23 03:41 UTC
Labels: translation
