### ISSUE TITLE
Delete getVersionForBrand stub

### ISSUE THREAD

**Issue by zepumph** [phetsims/chipper#683] opened 2018-06-13 21:26 UTC
In `getVersionForBrand.js`, @samreid and I see this todo, promoting to an issue:

` TODO: remove this stub once we merge to master (joist/preloads have usage)`

**Comment by ariel-phet** [comment] 2018-08-09 03:44
Requesting a volunteer....

**Comment by jonathanolson** [comment] 2018-08-09 16:20
Looks like a duplicate of https://github.com/phetsims/chipper/issues/697 which I fixed earlier this week. Closing.

**Closed by jonathanolson** 2018-08-09 16:20 UTC
Labels: meeting:developer
