### ISSUE TITLE
Potential conflict with cookies in Edge

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/chipper#888] opened 2020-02-24 21:28 UTC
Found during https://github.com/phetsims/QA/issues/482, but warning comes up with published sims.
A warning that Edge will start blocking cookies without a certain marker in the future comes up when using a sim with dev tools. Unsure what bit of code this is or how it might impact sims, so investigation may be called for. This is the chromium version of Edge.
![cookie](https://user-images.githubusercontent.com/41024075/75192654-e0744c00-5711-11ea-9227-594f6ee273e9.png)

**Comment by KatieWoe** [comment] 2020-02-24 21:30
A cookie associated with a resource at (sim) was set with `SameSite=None` but without `Secure`. A future release of Microsoft Edge will only deliver cookies marked `SameSite=None` if they are also marked `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at (website).

**Comment by ariel-phet** [comment] 2020-02-24 21:40
@mattpen can you take a quick look at this - is this something on the website side with how sims are delivered, or is this something with the sim file itself? My naive impression is there is nothing about the sim file itself that would specify cookies and this is more a website/server issue?

**Comment by jonathanolson** [comment] 2020-02-24 21:49
This looks more like it's related with Google Analytics (in my wheelhouse)

**Comment by mattpen** [comment] 2020-02-24 21:50
@KatieWoe - I can't recreate this.  I see this warning for a lot of pages on our website and it isn't limited to Edge.  The warning is related to GA tracking and those cookies are set by code run by google.  I don't see this warning when running a sim though, either in Edge or Chrome:

![image](https://user-images.githubusercontent.com/11747676/75194185-e1f34380-5714-11ea-80ca-595a248cb4e3.png)

![image](https://user-images.githubusercontent.com/11747676/75194213-eddf0580-5714-11ea-8e82-be0856041f4a.png)

**Comment by KatieWoe** [comment] 2020-02-24 21:52
I haven't seen it in chrome, but I see it in Edge. Like I said above though, I see it in chromium Edge. Your screenshot looks like the old Edge.

**Comment by zepumph** [comment] 2020-02-26 17:30
@samreid, @chrisklus, and I tested the following links in edge on windows 10

Microsoft Edge 44.18362.449.0
Microsoft EdgeHTML 18.18362

https://phet-dev.colorado.edu/modules-testing/build-an-atom/phet/build-an-atom_en_phet.html
https://phet.colorado.edu/sims/html/number-line-integers/latest/number-line-integers_en.html
https://phet.colorado.edu/sims/html/projectile-motion/latest/projectile-motion_en.html

And could not reproduce this problem.

**Comment by KatieWoe** [comment] 2020-02-26 17:33
I'm using Version 80.0.361.62 (Official build) (64-bit)

**Comment by zepumph** [comment] 2020-02-26 17:56
Ahh thanks! I went and downloaded the new and improved Edge (same version as you), and now get the error immediately:

![image](https://user-images.githubusercontent.com/6856943/75373008-e8e59780-5875-11ea-9a78-0f0c9b314447.png)

**Comment by mattpen** [comment] 2020-02-26 18:54
I'm running into Windows Update issues and can't currently install Edge 80 (stuck on 44, which is pre-chromium).  Interesting that this warning doesn't appear in the latest version of Chrome, as a lot of other pages are printing similar warnings.  Anyway for this page in particular, this is not website code but sim code, so moving to developer meeting per request from @ariel-phet.

**Comment by pixelzoom** [comment] 2020-03-05 19:42
3/5/20 dev meeting:

Related to Google analytics, so this is in @jonathanolson's wheelhouse.  Assigning to him.

**Comment by mattpen** [comment] 2020-08-07 22:15
My windows machine currently can't upgrade to the latest version of Edge, removing assignment.

**Comment by mattpen** [comment] 2020-08-17 16:36
I was able to install Edge Beta 85.  This problem is not present in this version. Perhaps it is fixed?

**Comment by jonathanolson** [comment] 2020-08-17 16:42
I'm seeing warnings about cookies on the website itself (vimeo, google), but I'm not seeing any warnings about cookies when running simulations directly. I'm also seeing our google analytics send out properly from sims.

@KatieWoe can you see if we're getting warnings with sims with the latest Edge version? (Tested with version 84).

**Comment by KatieWoe** [comment] 2020-08-17 16:52
I'm not seeing this in the sim now. I am seeing some odd warning in the website and when launching the sim, but I don't know if they are connected.

**Comment by mattpen** [comment] 2020-08-17 17:02
@KatieWoe - Can you please provide details for "some odd warning in the website" and then assign me and @jonathanolson ?

**Comment by KatieWoe** [comment] 2020-08-17 17:15
Most were tracking prevention warnings. an error showed up and flashed quickly as you click on a link to go to a sim.
`Uncaught syntax [rror: missing ) after argument list`
![warninganderrors](https://user-images.githubusercontent.com/41024075/90424150-e0c72180-e07a-11ea-8b87-a864a045fbb9.gif)

**Comment by mattpen** [comment] 2020-08-17 17:21
This doesn't look like it affects sims, removing @jonathanolson's assignment

**Comment by mattpen** [comment] 2020-09-22 20:09
https://docs.microsoft.com/en-us/microsoft-edge/web-platform/tracking-prevention

This newer message looks like a byproduct of a new feature in Edge.  This is probably expected behavior. This doesn't seem to be causing any problems, so I'm going to close this issue.

**Closed by mattpen** 2020-09-22 20:09 UTC
Labels: type:bug
