### ISSUE TITLE
CT line numbers don't respect sourcemaps

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#1140] opened 2021-11-04 03:20 UTC
Discovered in https://github.com/phetsims/gravity-and-orbits/issues/413. CT reports line numbers based on the chipper/dist and doesn't include a sourcemap, so it doesn't correspond to the line numbers in the *.ts files.  Why is the sourcemap being ignored here?

**Comment by jonathanolson** [comment] 2021-11-11 16:39
The errors are still based on JS, it looks like we'd need to use a tool like https://github.com/mifi/stacktracify to get sourcemapped errors handled properly in CT with typescript.

**Comment by samreid** [comment] 2021-11-24 01:59
stacktracify looks like a trivial wrapper around https://www.npmjs.com/package/source-map and https://www.npmjs.com/package/stacktrace-parser, with extra things we probably wouldn't use such as meow, clipboardy and fs-extra.

**Comment by samreid** [comment] 2021-11-24 02:29
@jonathanolson can you point me in the right direction for where the stack is presented in CT?

**Comment by jonathanolson** [comment] 2021-12-03 22:54
https://github.com/phetsims/chipper/blob/cd4580440fb656d6ced70ac30323fb23838e1f96/js/initialize-globals.js#L873-L885 is where the stack is JSON'ed.

**Comment by samreid** [comment] 2021-12-13 00:34
I noticed the snippet above is in in initialize-globals, which runs with every sim.  I'm not convinced we should add source-map and stacktrace-parser to our sim downloads, so I checked where this error arrives in CT.  `'continuous-test-error'` also appears in aqua/js/client/sim-test.js, but this file is a preload.   @jonathanolson is that the appropriate place to put stacktrace-parser and source-map dependencies?

**Comment by jonathanolson** [comment] 2021-12-13 20:58
Presumably we'd put it in aqua, since that's where we'd want to take the JS stack and convert it to the TS stack. Does the transpile generate source maps?

**Comment by samreid** [comment] 2021-12-14 05:19
Yes, I think they are inlined at the bottom of the file.  I'll take a look.

**Comment by pixelzoom** [comment] 2022-02-16 15:05
Can we raise the priority of this?  Investigating CT issues has gotten much more time consuming, now that I have to manually locate and inspect .js files under chipper/dist/js.

**Comment by samreid** [comment] 2022-02-17 15:51
I'll try to do this by the end of March.

**Comment by jessegreenberg** [comment] 2022-02-17 19:13
Checked in during 2/17/22 - This is not ideal, and the end of March timeline seems appropriate.

**Comment by pixelzoom** [comment] 2022-03-28 16:25
Not all CT errors are reproducible locally, and manually mapping from .js to .ts is really getting old.

**Comment by samreid** [comment] 2022-03-29 23:38
@zepumph and I started on this today.  We were using https://www.npmjs.com/package/source-map and https://www.npmjs.com/package/stacktrace-parser in sim-test.js like so:

<details>

```diff

Index: html/sim-test.html
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/html/sim-test.html b/html/sim-test.html
--- a/html/sim-test.html	(revision a4eaf2aa797b059be4550bc2274e4e148618fcde)
+++ b/html/sim-test.html	(date 1648585313189)
@@ -15,6 +15,9 @@
 <script src="../../sherpa/lib/lodash-4.17.4.min.js"></script>
 <script src="../build/QueryStringMachine.js"></script>
 <script src="../js/client/client.js"></script>
+
+<script src="https://unpkg.com/source-map@0.7.3/dist/source-map.js"></script>
+
 <script src="../js/client/sim-test.js"></script>
 </body>
 </html>
Index: js/client/sim-test.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/client/sim-test.js b/js/client/sim-test.js
--- a/js/client/sim-test.js	(revision a4eaf2aa797b059be4550bc2274e4e148618fcde)
+++ b/js/client/sim-test.js	(date 1648585788744)
@@ -6,6 +6,187 @@
  * @author Jonathan Olson <jonathan.olson@colorado.edu>
  */
 
+const UNKNOWN_FUNCTION = '<unknown>';
+
+// ????
+sourceMap.SourceMapConsumer.initialize( {
+  "lib/mappings.wasm": "https://unpkg.com/source-map@0.7.3/lib/mappings.wasm"
+} );
+
+/**
+ * This parses the different stack traces and puts them into one format
+ * This borrows heavily from TraceKit (https://github.com/csnover/TraceKit)
+ */
+function parse( stackString ) {
+  const lines = stackString.split( '\n' );
+
+  return lines.reduce( ( stack, line ) => {
+    const parseResult =
+      parseChrome( line ) ||
+      parseWinjs( line ) ||
+      parseGecko( line ) ||
+      parseNode( line ) ||
+      parseJSC( line );
+
+    if ( parseResult ) {
+      stack.push( parseResult );
+    }
+
+    return stack;
+  }, [] );
+}
+
+const chromeRe = /^\s*at (.*?) ?\(((?:file|https?|blob|chrome-extension|native|eval|webpack|<anonymous>|\/|[a-z]:\\|\\\\).*?)(?::(\d+))?(?::(\d+))?\)?\s*$/i;
+const chromeEvalRe = /\((\S*)(?::(\d+))(?::(\d+))\)/;
+
+function parseChrome( line ) {
+  const parts = chromeRe.exec( line );
+
+  if ( !parts ) {
+    return null;
+  }
+
+  const isNative = parts[ 2 ] && parts[ 2 ].indexOf( 'native' ) === 0; // start of line
+  const isEval = parts[ 2 ] && parts[ 2 ].indexOf( 'eval' ) === 0; // start of line
+
+  const submatch = chromeEvalRe.exec( parts[ 2 ] );
+  if ( isEval && submatch != null ) {
+    // throw out eval line/column and use top-most line/column number
+    parts[ 2 ] = submatch[ 1 ]; // url
+    parts[ 3 ] = submatch[ 2 ]; // line
+    parts[ 4 ] = submatch[ 3 ]; // column
+  }
+
+  return {
+    file: !isNative ? parts[ 2 ] : null,
+    methodName: parts[ 1 ] || UNKNOWN_FUNCTION,
+    arguments: isNative ? [ parts[ 2 ] ] : [],
+    lineNumber: parts[ 3 ] ? +parts[ 3 ] : null,
+    column: parts[ 4 ] ? +parts[ 4 ] : null,
+  };
+}
+
+const winjsRe = /^\s*at (?:((?:\[object object\])?.+) )?\(?((?:file|ms-appx|https?|webpack|blob):.*?):(\d+)(?::(\d+))?\)?\s*$/i;
+
+function parseWinjs( line ) {
+  const parts = winjsRe.exec( line );
+
+  if ( !parts ) {
+    return null;
+  }
+
+  return {
+    file: parts[ 2 ],
+    methodName: parts[ 1 ] || UNKNOWN_FUNCTION,
+    arguments: [],
+    lineNumber: +parts[ 3 ],
+    column: parts[ 4 ] ? +parts[ 4 ] : null,
+  };
+}
+
+const geckoRe = /^\s*(.*?)(?:\((.*?)\))?(?:^|@)((?:file|https?|blob|chrome|webpack|resource|\[native).*?|[^@]*bundle)(?::(\d+))?(?::(\d+))?\s*$/i;
+const geckoEvalRe = /(\S+) line (\d+)(?: > eval line \d+)* > eval/i;
+
+function parseGecko( line ) {
+  const parts = geckoRe.exec( line );
+
+  if ( !parts ) {
+    return null;
+  }
+
+  const isEval = parts[ 3 ] && parts[ 3 ].indexOf( ' > eval' ) > -1;
+
+  const submatch = geckoEvalRe.exec( parts[ 3 ] );
+  if ( isEval && submatch != null ) {
+    // throw out eval line/column and use top-most line number
+    parts[ 3 ] = submatch[ 1 ];
+    parts[ 4 ] = submatch[ 2 ];
+    parts[ 5 ] = null; // no column when eval
+  }
+
+  return {
+    file: parts[ 3 ],
+    methodName: parts[ 1 ] || UNKNOWN_FUNCTION,
+    arguments: parts[ 2 ] ? parts[ 2 ].split( ',' ) : [],
+    lineNumber: parts[ 4 ] ? +parts[ 4 ] : null,
+    column: parts[ 5 ] ? +parts[ 5 ] : null,
+  };
+}
+
+const javaScriptCoreRe = /^\s*(?:([^@]*)(?:\((.*?)\))?@)?(\S.*?):(\d+)(?::(\d+))?\s*$/i;
+
+function parseJSC( line ) {
+  const parts = javaScriptCoreRe.exec( line );
+
+  if ( !parts ) {
+    return null;
+  }
+
+  return {
+    file: parts[ 3 ],
+    methodName: parts[ 1 ] || UNKNOWN_FUNCTION,
+    arguments: [],
+    lineNumber: +parts[ 4 ],
+    column: parts[ 5 ] ? +parts[ 5 ] : null,
+  };
+}
+
+const nodeRe = /^\s*at (?:((?:\[object object\])?[^\\/]+(?: \[as \S+\])?) )?\(?(.*?):(\d+)(?::(\d+))?\)?\s*$/i;
+
+function parseNode( line ) {
+  const parts = nodeRe.exec( line );
+
+  if ( !parts ) {
+    return null;
+  }
+
+  return {
+    file: parts[ 2 ],
+    methodName: parts[ 1 ] || UNKNOWN_FUNCTION,
+    arguments: [],
+    lineNumber: +parts[ 3 ],
+    column: parts[ 4 ] ? +parts[ 4 ] : null,
+  };
+}
+
+// See https://github.com/mifi/stacktracify/blob/master/index.js
+const readSourcemap = async str => {
+
+  const stack = parse( str );
+  if ( stack.length === 0 ) {
+    throw new Error( 'No stack found' );
+  }
+
+  const header = str.split( '\n' ).find( line => line.trim().length > 0 );
+
+  if ( header ) {
+    console.log( header );
+  }
+
+  stack.forEach( ( { methodName, lineNumber, column } ) => {
+    try {
+      if ( lineNumber === null || lineNumber < 1 ) {
+        console.log( `    at ${methodName || ''}` );
+      }
+      else {
+
+
+        // WTF? promise?
+        const smc = await new SourceMapConsumer( mapContent );
+
+        const pos = smc.originalPositionFor( { line: lineNumber, column: column } );
+        if ( pos && pos.line !== null ) {
+          console.log( `    at ${pos.name || ''} (${pos.source}:${pos.line}:${pos.column})` );
+        }
+
+        // console.log('src', smc.sourceContentFor(pos.source));
+      }
+    }
+    catch( err ) {
+      console.log( `    at FAILED_TO_PARSE_LINE` );
+    }
+  } );
+};
 
 ( () => {
   const options = QueryStringMachine.getAll( {
@@ -70,7 +251,10 @@
       // Sent by Joist due to the postMessage* query parameters
       if ( data.type === 'continuous-test-error' ) {
         clearTimeout( timeoutID );
-        aqua.simpleFail( `${failPrefix + data.message}\n${data.stack}` );
+
+        const newStack = await readSourcemap( data.stack );
+
+        aqua.simpleFail( `${failPrefix + data.message}\n${newStack}` );
       }
       else if ( data.type === 'continuous-test-unload' ) {
         clearTimeout( timeoutID );

```

</details>

It seems like it could be 4-8 more hours to get something working for this.  But it also led to questions about how this should behave and how it should be implemented.  

* Should we retain any of the chipper/dist stack?  Or should it all be replaced by the sourcemapped stack?
* What about JS files that do not have a source map?  Is it OK to have those point to the chipper/dist version, or should we build our own mapping to look up the corresponding paths?
* The stack trace refers to files with paths like: `> at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648586211726/chipper/dist/js/axon/js/TinyEmitter.js:68:9)`.  A typical stack trace has maybe 5-20 lines like this.  Loading the source map for each of these could be 5-20 network accesses to load JS files in order to read their sourcemap.  Is it OK to add 5-20x network delays per stack trace?  Alternatively, is there a stable way to load these files on the server via file access (instead of network access)?  Alternatively, would it be OK if it shows the chipper/dist stack trace, but if you click on one line, it lazily converts that one line to the source file?

In our discussions, I mentioned to @zepumph that I would have used this functionality 1-2 times in the last month.  Having the correct source map could have saved me up to 30 seconds each time. Therefore, running a cost benefit analysis it seems: just for me, the breakeven point would be in 6 hrs * 60 min/hr = 360 minutes => 360 minutes * 1 month/minute = 360 months = 30 years.  But it sounded much more important for other team members, so let's continue working on it.

**Comment by pixelzoom** [comment] 2022-03-30 00:00
Sad to hear that something so fundamentally necessary to a transpiled language is so difficult.  Also sorry to hear that you don't feel that you're going to benefit from what seems like a basic/necessary feature of a transpiled language.   There may be some consolation in the fact that, as the amount of TypeScript code increases, this is likely to get worse, not better.

I've been hitting a fair number of problems that are not in my code, and are not easily reproduced locally.  So I find myself having to manually map from .js to .ts about 2-3 times per week.  Do I feel like it's a waste of my time? Yes. Is it a _major_ waste of my time? No.  Does it irritate the heck out of me because it's something basic that's missing? Absolutely.

**Comment by samreid** [comment] 2022-03-30 00:25
Sounds good and I'm happy to keep working on this.

Do you see any need for any chipper/dist references in the stacktrace (first bullet)?

For JS files that do not have a source map, is it OK to point to the chipper/dist line numbers, or should we remap those to the corresponding directories? (second bullet)

Would it be OK if the sourcemap is processed lazily and just on a single-line basis, like when you click on a line number from CT? (third bullet point).  Are we OK with network delays from this, or should we try to get this from filesystem loads?

Are there any other improvements that should be made at the same time, like an easier way to copy the relative path from a stack trace?

**Comment by samreid** [comment] 2022-03-30 03:06
Also, do we need to do anything about built stack traces, or is this issue for the unbuilt sims only?

**Comment by samreid** [comment] 2022-03-30 04:51
I committed an initial working version to a new branch "sourcemaps".  aqua is the only branched repo.  The CT interface  looks like this in my working copy:

<img width="1095" alt="image" src="https://user-images.githubusercontent.com/679486/160753490-fe93ebc3-0606-47c3-bcc7-39b15cde81dd.png">

I listed some questions for discussion with the reviewer in TODO comments. @zepumph can you please take a look?  A short meeting or co-review may also be nice.

**Comment by samreid** [comment] 2022-03-30 12:57
Also brainstorming a potential embellishment: what if the stack traces also output the corresponding source lines?  For instance, for the stack trace pictured in the preceding comment, it could read:

```ts
throw new Error( logMessage );
↑
assert && assert( false, 'kicky' );
↑
listener: () => model.scheduleKicks( numberToKick ),
↑
listener( ...args );
↑
this.tinyEmitter.emit( ...args );
↑
this.firedEmitter.emit();
```

I thought this may sometimes additionally cue what is happening. But I think the main point is to help the developer get to the problem in their own working copy.  So I'm brainstorming this halfheartedly, but I hadn't heard of this before so I thought I'd mention it.

**Comment by pixelzoom** [comment] 2022-03-30 15:03
> Do you see any need for any chipper/dist references in the stacktrace (first bullet)?

I don't see any need for this. Ideally we should be able to ignore chipper/dist/, unless there's a bug introduced by transpilation.

> For JS files that do not have a source map, is it OK to point to the chipper/dist line numbers, or should we remap those to the corresponding directories? (second bullet)

If .js files in chipper/dist/ are different than the source .js files, then no, not the chipper/dist/ line numbers.   In general, we want the line numbers from the files that were the _inputs_ to transpilation, not the outputs.

> Would it be OK if the sourcemap is processed lazily and just on a single-line basis, like when you click on a line number from CT? (third bullet point). Are we OK with network delays from this, or should we try to get this from filesystem loads?

It depends on how long the delay is. If it's seconds, probably not OK, because it would make it more difficult to "explore" CT when there's a lot of red.  Another approach might be to show the transpiled stack track in CT, with an options (button or something) to appy the sourcemap for a specific stack trace.

> Are there any other improvements that should be made at the same time, like an easier way to copy the relative path from a stack trace?
> ...
> Also brainstorming a potential embellishment: what if the stack traces also output the corresponding source lines? ...

I don't think this is necessary.  A standard stack trace that references the source files (the inputs to transpilation) is sufficient.

**Comment by zepumph** [comment] 2022-03-31 16:41
>Would it be OK if the sourcemap is processed lazily and just on a single-line basis, like when you click on a line number from CT? (third bullet point). Are we OK with network delays from this, or should we try to get this from filesystem loads?

I think it would be best to have this computed when the error occurs in the sim-test. I can't think of any reason why we need to store the incorrect (from dist/) stacktrace anywhere in the server or reporting. If network trouble is the worry, let's quantify that before we try to optimize around it.

**Comment by samreid** [comment] 2022-03-31 19:26
Today we discussed that it isn't important to get the built sourcemaps working on CT.  We should see if built sourcemaps are working (from the webpack/babel phase), but no need to make changes for how they are reported on CT.

**Comment by samreid** [comment] 2022-04-12 15:00
The transpiled stack trace does not include the full path:

```
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: schedule kicks
Error: schedule kicks
at (SoccerModel.ts:191:10)
at scheduleKicks (KickButtonGroup.ts:72:30)
at listener (TinyEmitter.ts:93:8)
at emit (Emitter.ts:65:21)
at emit (PushButtonModel.ts:179:22)
at fire (PushButtonModel.ts:120:15)
at listener (TinyEmitter.ts:93:8)
at emit (Property.ts:276:22)
at _notifyListeners (Property.ts:208:13)
at set (ButtonModel.ts:187:24)
id: local
Snapshot from 4/11/2022, 10:46:59 AM

----------------------------------
```

Hopefully that is OK.

**Comment by samreid** [comment] 2022-04-12 15:14
I notified slack:

> Moved to this morning: I’m planning to merge changes to master today that should enable correct stack trace lines on CT for https://github.com/phetsims/chipper/issues/1140.  So this could be somewhat destabilizing until it is ironed out.

I merged the branch to master and will manually pull the updated code on aqua.

**Comment by samreid** [comment] 2022-04-12 15:54
I'm seeing the first transpiled stack trace on CT:

```
Error: Assertion failed: recalculateVelocityAndAcceleration: N=7 i=2 velocity=Vector2(0, 1.247873001451245), expected non-zero x component
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1649776725331/assert/js/assert.js:25:13)
at assert (OneDimensionModel.js:304:12)
at recalculateVelocityAndAcceleration (OneDimensionModel.js:270:9)
at setVerletPositions (OneDimensionModel.js:241:11)
at singleStep (OneDimensionModel.js:221:13)
at step (Sim.js:288:21)
at apply (PhetioAction.ts:123:16)
at execute (Sim.js:947:30)
at stepSimulation (Sim.js:937:11)
at stepOneFrame (Sim.js:912:11)
id: Bayes Chrome
Snapshot from 4/12/2022, 9:18:45 AM
```

I'll notify slack.  I think I'll open a side issue about dealing with the built stack traces.

**Comment by samreid** [comment] 2022-04-12 16:39
For unknown reasons, in the same column, there are some chipper/dist in this stack trace:

```
Uncaught Error: Uncaught Error: Assertion failed
Error: Assertion failed
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1649776725331/assert/js/assert.js:25:13)
at NumberProperty.validateNumberAndRangeProperty (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1649776725331/chipper/dist/js/axon/js/NumberProperty.js:83:17)
at NumberProperty.validateNumberProperty (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1649776725331/chipper/dist/js/axon/js/NumberProperty.js:207:14)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1649776725331/chipper/dist/js/axon/js/NumberProperty.js:117:68
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1649776725331/chipper/dist/js/axon/js/TinyEmitter.js:68:9)
at NumberProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1649776725331/chipper/dist/js/axon/js/Property.js:218:23)
at NumberProperty.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1649776725331/chipper/dist/js/axon/js/Property.js:147:14)
at NumberProperty.set value [as value] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1649776725331/chipper/dist/js/axon/js/Property.js:288:10)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1649776725331/chipper/dist/js/circuit-construction-kit-common/js/view/CircuitElementEditContainerNode.js:75:66
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1649776725331/chipper/dist/js/axon/js/TinyEmitter.js:68:9)
id: Bayes Chrome
Snapshot from 4/12/2022, 9:18:45 AM
```

Maybe because it is a phet-io-state fuzz test?

**Comment by samreid** [comment] 2022-04-19 16:14
I applied the same changes from sim-test.js to the other 3 tests mentioned above in this patch:

<details>

```diff

Index: html/pageload-test.html
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/html/pageload-test.html b/html/pageload-test.html
--- a/html/pageload-test.html	(revision 7438775fe6047d88d6d30fc8bd8d0daa7d466918)
+++ b/html/pageload-test.html	(date 1650381839112)
@@ -15,6 +15,11 @@
 <script src="../../sherpa/lib/lodash-4.17.4.min.js"></script>
 <script src="../build/QueryStringMachine.js"></script>
 <script src="../js/client/client.js"></script>
+
+<script src="../../sherpa/lib/source-map-0.7.3.js"></script>
+<script src="../../sherpa/lib/stack-trace-parser-0.1.7.js"></script>
+
+<script src="../js/client/transpileStacktrace.js"></script>
 <script src="../js/client/pageload-test.js"></script>
 </body>
 </html>
Index: html/wrapper-test.html
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/html/wrapper-test.html b/html/wrapper-test.html
--- a/html/wrapper-test.html	(revision 7438775fe6047d88d6d30fc8bd8d0daa7d466918)
+++ b/html/wrapper-test.html	(date 1650381704642)
@@ -15,6 +15,11 @@
 <script src="../../sherpa/lib/lodash-4.17.4.min.js"></script>
 <script src="../build/QueryStringMachine.js"></script>
 <script src="../js/client/client.js"></script>
+
+<script src="../../sherpa/lib/source-map-0.7.3.js"></script>
+<script src="../../sherpa/lib/stack-trace-parser-0.1.7.js"></script>
+
+<script src="../js/client/transpileStacktrace.js"></script>
 <script src="../js/client/wrapper-test.js"></script>
 </body>
 </html>
Index: js/client/wrapper-test.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/client/wrapper-test.js b/js/client/wrapper-test.js
--- a/js/client/wrapper-test.js	(revision 7438775fe6047d88d6d30fc8bd8d0daa7d466918)
+++ b/js/client/wrapper-test.js	(date 1650381625343)
@@ -49,7 +49,7 @@
   const testInfo = JSON.parse( aqua.options.testInfo );
 
   // handling messages from sims
-  window.addEventListener( 'message', evt => {
+  window.addEventListener( 'message', async evt => {
     if ( typeof evt.data !== 'string' ) {
       return;
     }
@@ -61,7 +61,9 @@
 
       // Sent by Joist due to the postMessage* query parameters
       if ( data.type === 'continuous-test-wrapper-error' ) {
-        aqua.simpleFail( `${data.message}\n${data.stack}` );
+
+        const transpiledStacktrace = await window.transpileStacktrace( data.stack );
+        aqua.simpleFail( `${data.message}\n${transpiledStacktrace}` );
       }
       else if ( data.type === 'continuous-test-wrapper-unload' ) {
         aqua.simpleFail( 'Unloaded frame before complete, window.location probably changed' );
Index: html/qunit-test.html
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/html/qunit-test.html b/html/qunit-test.html
--- a/html/qunit-test.html	(revision 7438775fe6047d88d6d30fc8bd8d0daa7d466918)
+++ b/html/qunit-test.html	(date 1650381804754)
@@ -15,6 +15,11 @@
 <script src="../../sherpa/lib/lodash-4.17.4.min.js"></script>
 <script src="../build/QueryStringMachine.js"></script>
 <script src="../js/client/client.js"></script>
+
+<script src="../../sherpa/lib/source-map-0.7.3.js"></script>
+<script src="../../sherpa/lib/stack-trace-parser-0.1.7.js"></script>
+
+<script src="../js/client/transpileStacktrace.js"></script>
 <script src="../js/client/qunit-test.js"></script>
 </body>
 </html>
Index: js/client/qunit-test.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/client/qunit-test.js b/js/client/qunit-test.js
--- a/js/client/qunit-test.js	(revision 7438775fe6047d88d6d30fc8bd8d0daa7d466918)
+++ b/js/client/qunit-test.js	(date 1650381804750)
@@ -55,7 +55,7 @@
   // Supports old tests (which do not know when they are done)
   let id = setTimeout( done, options.duration );
 
-  window.addEventListener( 'message', evt => {
+  window.addEventListener( 'message', async evt => {
     if ( typeof evt.data !== 'string' ) {
       return;
     }
@@ -87,7 +87,9 @@
     }
     else if ( data.type === 'error' ) {
       clearTimeout( id );
-      error = data.message + data.stack;
+
+      const transpiledStacktrace = await window.transpileStacktrace( data.stack );
+      error = data.message + transpiledStacktrace;
       done();
     }
   } );
Index: js/client/pageload-test.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/client/pageload-test.js b/js/client/pageload-test.js
--- a/js/client/pageload-test.js	(revision 7438775fe6047d88d6d30fc8bd8d0daa7d466918)
+++ b/js/client/pageload-test.js	(date 1650381895236)
@@ -29,7 +29,7 @@
   }, options.duration );
 
   // handling messages from the page
-  window.addEventListener( 'message', evt => {
+  window.addEventListener( 'message', async evt => {
     if ( typeof evt.data !== 'string' ) {
       return;
     }
@@ -41,7 +41,8 @@
       aqua.simplePass();
     }
     else if ( data.type === 'pageload-error' ) {
-      aqua.simpleFail( `${data.message}\n${data.stack}` );
+      const transpiledStacktrace = await window.transpileStacktrace( data.stack );
+      aqua.simpleFail( `${data.message}\n${transpiledStacktrace}` );
     }
   } );
 } )();

```

</details>

I followed the instructions in https://github.com/phetsims/chipper/issues/1140#issuecomment-1096849609 to set up for local testing.  I started with the pageload tests, and set up perennial's list like so:

```ts
// Page-load tests (non-built)
[
  {
    repo: 'dot',
    urls: [
      'tests/playground.html'
    ]
  }
].forEach( ( { repo, urls } ) => {
  urls.forEach( pageloadRelativeURL => {
    tests.push( {
      test: [ repo, 'pageload', `/${pageloadRelativeURL}` ],
      type: 'pageload-test',
      url: `${repo}/${pageloadRelativeURL}`,
      priority: 4 // Fast to test, so test them more
    } );
  } );
} );

console.log( JSON.stringify( tests, null, 2 ) );
```

I tried to simulate an error by adding this code:

```diff
Index: js/Bounds2.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/Bounds2.ts b/js/Bounds2.ts
--- a/js/Bounds2.ts	(revision 53f9d3561d00a3580f82210422937265c8442a8e)
+++ b/js/Bounds2.ts	(date 1650383729172)
@@ -418,6 +418,10 @@
     }
   }
 
+  throwError() {
+    throw new Error( 'hello' );
+  }
+
   /**
    * The smallest bounds that contains both this bounds and the input bounds, returned as a copy.
    *
Index: tests/playground.html
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/tests/playground.html b/tests/playground.html
--- a/tests/playground.html	(revision 53f9d3561d00a3580f82210422937265c8442a8e)
+++ b/tests/playground.html	(date 1650383838451)
@@ -56,6 +56,7 @@
 
   window.triDebug = function( triangulation ) {
     var bounds = dot.Bounds2.NOTHING.copy();
+    bounds.throwError();
     for ( var i = 0; i < triangulation.vertices.length; i++ ) {
       bounds.addPoint( triangulation.vertices[ i ].point );
     }
@@ -165,6 +166,9 @@
       }
     } );
   };
+
+  var bounds = dot.Bounds2.NOTHING.copy();
+  bounds.throwError();
 </script>
 </body>
 </html>
```

However, CT kept saying dot is fully green.

<img width="499" alt="image" src="https://user-images.githubusercontent.com/679486/164048510-5a13d977-af7a-47c8-9fde-e1a2c5b9bfca.png">

So I'm not sure how to test this.  @zepumph or @jonathanolson should we do one of the following?

* Collaboration/pairing meeting to make sure these other wrappers are transpiling as expected?
* Reassign to @zepumph or @jonathanolson to test asynchronously?
* Push the changes to master and hope for the best?

What do you recommend?

**Comment by samreid** [comment] 2022-04-19 16:56
@jonathanolson and I discovered that dot is not pointing to chipper/dist.  When we switched the test to use scenery/playground, it correctly transpiled.  We discussed whether it was worth another 30 minutes of local testing or not, and we both felt confident enough to push the changes to master/production and see how it goes on CT.

**Comment by samreid** [comment] 2022-04-19 17:16
I pushed the changes above.  Will need to restart CT to make sure they are running.

**Closed** 2022-04-21 18:15 UTC
Labels: status:ready-for-review, dev:typescript
