### ISSUE TITLE
refactor LicenseEntryClassifier.js as isAcceptableLicenseEntry.js

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#240] opened 2015-08-10 18:22 UTC
... as described in https://github.com/phetsims/chipper/issues/227:

• rename to isAcceptableLicenseEntry.js
• return a function instead of a collection of static functions
• handle the brand test

**Comment by pixelzoom** [comment] 2015-08-10 19:14
This is done. Over to @samreid for review.

**Comment by samreid** [comment] 2015-08-10 20:10
Looks like there is a new problem in loading sims with audio.  Not sure if it was caused by this work or not.  I'll investigate.

**Comment by samreid** [comment] 2015-08-10 20:10
```
forces-and-motion-basics samreid$ grunt --lint=false
Running "clean" task

Running "set-preload" task

Running "before-requirejs-build" task

Running "requirejs:build" (requirejs) task
>> Error: Error: Loader plugin did not call the load callback in the build:
>> audio:
>>   audio!VIBE/empty.mp3: Error: Error for /Users/samreid/github/vibe/js/../audio/empty.mp3
>>   audio!FORCES_AND_MOTION_BASICS/golf-clap: Error: Error for /Users/samreid/github/forces-and-motion-basics/js/../audio/golf-clap.mp3Error for /Users/samreid/github/forces-and-motion-basics/js/../audio/golf-clap.ogg
>> Module loading did not complete for: forces-and-motion-basics-main, FORCES_AND_MOTION_BASICS/ForcesAndMotionBasicsSim, FORCES_AND_MOTION_BASICS/netforce/view/NetForceScreenView, VIBE/Sound
>>     at Function.build.checkForErrors (/Users/samreid/github/forces-and-motion-basics/node_modules/requirejs/bin/r.js:29387:19)
Warning: Task "requirejs:build" failed. Use --force to continue.

Aborted due to warnings.
```

**Comment by samreid** [comment] 2015-08-10 20:11
I think I have found the error, a missing !.  Testing and will commit shortly.

**Comment by samreid** [comment] 2015-08-10 20:13
Bug was introduced in d1485e9d934139887586bba5c2820239a5c79856

**Comment by samreid** [comment] 2015-08-10 20:14
Fixed above.  I didn't see any other issues when I reviewed the changes above.  Closing.

**Closed by samreid** 2015-08-10 20:14 UTC

**Comment by pixelzoom** [comment] 2015-08-10 20:22
Thanks for catching that.
