### ISSUE TITLE
Name collisions with built-in types makes adding imports painful

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#1270] opened 2022-06-30 05:26 UTC
In Slack#typescript, I wrote:

> PhET has quite a few classes whose names collide with built-in types. And it’s a real drag having to manually import them in WebStorm. I’m having to manually deal with Node, Text, Range, and (sometimes) Image dozens of times per day. Has anyone discovered a way around this?

Other developers are experiencing this problem.

@samreid wrote:
> I have the same problem and no good workaround.  (I manually add the imports, usually by copy/pasting a similar import).  If nobody else has good workarounds, maybe we would consider names like `SceneryNode` etc.

@marlitas wrote:
> This frustration is constant. With Node I sometimes get the type error that allows me to quickly import the correct one in IntelliJ, but haven't looked into if there's a way to make that a bit more automatic.

Adding this to developer meeting for discussion.

**Comment by jessegreenberg** [comment] 2022-06-30 18:02
@chrisklus @zepumph suggested a different key command/operation to get it to auto import by typing only part of the type name.

@liam-mulhall also suggested renaming these files to avoid collisions.
@jonathanolson: This would be a big commitment and involve changing a lot of documentation. But it is possible.

**Comment by samreid** [comment] 2022-07-05 17:25
Maybe open an issue with JetBrains describing the problem and asking how they would solve it?

**Comment by zepumph** [comment] 2022-08-04 18:13
The dev team thinks that this is a big bummer, and we'd like to proceed with a jetbrains issue. We @jessegreenberg  on the case!

![image](https://user-images.githubusercontent.com/6856943/182921532-d6b686d2-eda6-4032-a86a-7c5c6a26b910.png)

**Comment by jessegreenberg** [comment] 2022-08-04 23:38
Before making an issue for jetbrains I wanted to try a test case in a more simple project and found that WebStorm does support this:
![image](https://user-images.githubusercontent.com/6396244/182972403-9bafa552-22f1-47bc-85ac-373108b4b5b4.png)

Here is the basic project structure I made:
<details>

![image](https://user-images.githubusercontent.com/6396244/182972796-84c818cb-b1c8-46dc-8945-0bd1ce32ea93.png)
</details>

So what is different about PhET's setup?

**Comment by jessegreenberg** [comment] 2022-08-05 15:13
I believe this problem is the same as https://youtrack.jetbrains.com/issue/WEB-54951, which also prevents us from auto-import on code completion when importing across repos. When I added package.jsons under scenery/ and project/ in my demo importing, built-in types broke (as did auto-import on tab completion).

**Comment by samreid** [comment] 2022-08-08 12:49
There is also a similar paper trail in https://github.com/phetsims/chipper/issues/1166 and https://github.com/phetsims/chipper/issues/1172 which lead to https://youtrack.jetbrains.com/issue/WEB-54083#focus=Comments-27-5665822.0-0

**Comment by jessegreenberg** [comment] 2022-08-08 15:01
Thanks! Yes I think it is the same problem. Auto imports for Node/Text/Image all work great under scenery/.

**Comment by jessegreenberg** [comment] 2022-09-02 21:13
The script from https://github.com/phetsims/chipper/issues/1320 can be used to get around this problem.

**Comment by samreid** [comment] 2022-09-28 14:59
@jessegreenberg can this be removed from the project board?

**Comment by jessegreenberg** [comment] 2022-10-05 14:22
Yea, and I think we can close it because this can be collapsed into https://github.com/phetsims/chipper/issues/1166. It is caused by the same WebStorm problem.

**Closed by jessegreenberg** 2022-10-05 14:22 UTC
Labels: dev:typescript
