### ISSUE TITLE
Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable ...

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#812] opened 2019-11-06 00:51 UTC
This line in reportThirdParty.js is resulting in a warning during deploy:

`process.env.NODE_TLS_REJECT_UNAUTHORIZED = '0';`

Here's the situation where I experienced it:

```
% node --version
v12.13.0
% npm -version
6.12.0
% % cd vector-addition
% grunt production --brands=phet --branch=1.0
...
info: npm update on vector-addition
info: npm update on chipper
info: getting metadata request with https://phet.colorado.edu/services/metadata/1.0/simulations?format=json&summary&type=html&simulation=vector-addition
Is the master checklist complete (e.g. are screenshots added to assets, etc.) [y/N]?>> 
(node:91718) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable 
to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
...
```
<br>

I was able to answer ‘y’ to the prompt, and the deploy seems to have completed successfully.

**Comment by pixelzoom** [comment] 2019-11-06 01:01
`NODE_TLS_REJECT_UNAUTHORIZED` was added to reportThirdParty.js by @matt, so I’ll start by assigning to him.

**Comment by mattpen** [comment] 2019-11-06 18:46
Duplicate of #788

**Closed by mattpen** 2019-11-06 18:46 UTC
